import { describe, it, expect } from "vitest";
import {
  AAMVA_VERSIONS,
  AAMVA_VERSION_KEYS,
  getFieldsForStateAndVersion,
  getMandatoryFields,
  isSupportedVersion
} from "../core/schema";
import { generateAAMVAPayload } from "../core/generator";
import { decodeAAMVA, decodePayload } from "../core/decoder";
import { evaluateFieldValue, getValidationIssues } from "../core/validation";
import { JURISDICTION_RULE_PACKS } from "../core/jurisdictionRules";
import type { AAMVAField } from "../core/schema";
import ilIdBaseline from "../core/conformance/vectors/il-v09-id-baseline.json";

// A complete, synthetic ID record that already lives in the repo, so these
// regressions need no hand-written stand-in for a real card.
const ID_VECTOR_INPUT = ilIdBaseline.input as Record<string, string>;

/**
 * Regression suite for the defects found in the bug review. Each block names
 * the behaviour that was wrong so a future change that reintroduces it fails
 * with an explanation rather than a bare assertion.
 */

/** A complete, valid v10 form for the given jurisdiction. */
function formFor(state: string, overrides: Record<string, string> = {}): Record<string, string> {
  return {
    DCA: "C",
    DCB: "NONE",
    DCD: "NONE",
    DBA: "01012029",
    DCS: "DOE",
    DAC: "JANE",
    DAD: "Q",
    DBD: "01012024",
    DBB: "02151990",
    DBC: "2",
    DAY: "BRO",
    DAU: "067 IN",
    DAG: "123 SAMPLE ST",
    DAI: "SPRINGFIELD",
    DAJ: state,
    DAK: "94110",
    DAQ: "D1234567",
    DCF: "SAMPLEDD12345",
    DCG: "USA",
    DDE: "N",
    DDF: "N",
    DDG: "N",
    ...overrides
  };
}

describe("the customer ID number is never invented", () => {
  const fields = getFieldsForStateAndVersion("CA", "10");

  it("blocks generation when DAQ is empty, even with auto-generation on", () => {
    // `autoGenerateDiscriminator` swept up every jurisdiction generator, which
    // included DAQ. An empty licence number therefore produced a barcode
    // carrying a random one instead of the missing-mandatory-field error, and
    // the value never appeared in the form the user was looking at.
    const data = formFor("CA");
    delete data.DAQ;

    expect(() =>
      generateAAMVAPayload("CA", "10", fields, data, {
        strictMode: true,
        autoGenerateDiscriminator: true
      })
    ).toThrow(/Missing mandatory fields.*Customer ID Number \(DAQ\)/s);
  });

  it("still auto-generates the document discriminator", () => {
    const data = formFor("CA");
    delete data.DCF;

    const payload = generateAAMVAPayload("CA", "10", fields, data, {
      strictMode: true,
      autoGenerateDiscriminator: true
    });

    expect(decodeAAMVA(payload).json?.DCF).toBeTruthy();
  });

  it("does not inject codes the selected version has no field for", () => {
    // v01 has no DCF or DDB. They were written into the caller's object anyway.
    const v01Fields = getFieldsForStateAndVersion("VA", "01");
    const data: Record<string, string> = {
      DAA: "DOE,JANE,Q",
      DAG: "123 SAMPLE ST",
      DAI: "RICHMOND",
      DAJ: "VA",
      DAK: "23219",
      DAQ: "D12345678",
      DBA: "20290101",
      DBB: "19900215",
      DBC: "F"
    };

    const payload = generateAAMVAPayload("VA", "01", v01Fields, data, {
      autoGenerateDiscriminator: true
    });

    expect(payload).not.toContain("DCF");
    expect(payload).not.toContain("DDB");
  });
});

describe("generateAAMVAPayload does not mutate its input", () => {
  it("leaves the caller's object exactly as it was passed", () => {
    const fields = getFieldsForStateAndVersion("CA", "10");
    const data = formFor("CA", { DAG: "123 sample st", DCS: "  doe  " });
    delete data.DCF;
    const before = JSON.stringify(data);

    generateAAMVAPayload("CA", "10", fields, data, {
      strictMode: false,
      autoGenerateDiscriminator: true
    });

    // Normalisation (uppercasing, trimming) and auto-fill both used to be
    // written straight back into the caller's object.
    expect(JSON.stringify(data)).toBe(before);
  });
});

describe("AAMVA version coverage", () => {
  it("defines every version from 01 to 11", () => {
    for (let i = 1; i <= 11; i++) {
      const key = String(i).padStart(2, "0");
      expect(isSupportedVersion(key), `version ${key}`).toBe(true);
    }
  });

  it("lists versions in ascending order for the pickers", () => {
    // Object.keys puts the integer-like "10"/"11" ahead of "01".."09", so every
    // dropdown built from it opened on version 10.
    expect(AAMVA_VERSION_KEYS).toEqual([
      "01",
      "02",
      "03",
      "04",
      "05",
      "06",
      "07",
      "08",
      "09",
      "10",
      "11"
    ]);
    expect([...AAMVA_VERSION_KEYS].sort()).toEqual([...AAMVA_VERSION_KEYS]);
    expect(AAMVA_VERSION_KEYS.length).toBe(Object.keys(AAMVA_VERSIONS).length);
  });

  it("builds a usable form and payload for 05, 06 and 07", () => {
    for (const version of ["05", "06", "07"]) {
      const fields = getFieldsForStateAndVersion("CA", version);
      expect(fields.length, `v${version} field count`).toBeGreaterThan(0);
      const payload = generateAAMVAPayload("CA", version, fields, formFor("CA"), {
        strictMode: false
      });
      expect(decodeAAMVA(payload).json?.version).toBe(version);
    }
  });

  it("rejects a version outside the table", () => {
    expect(isSupportedVersion("99")).toBe(false);
    expect(isSupportedVersion("")).toBe(false);
  });
});

describe("getMandatoryFields honours the jurisdiction", () => {
  it("returns exactly the required fields the form renders", () => {
    // It ignored `stateCode` entirely and read the version table directly. That
    // only agreed with the form by accident of the exclusion filter.
    for (const state of ["NY", "CT", "CA", "PR"]) {
      for (const version of AAMVA_VERSION_KEYS) {
        const shown = getFieldsForStateAndVersion(state, version).filter((f) => f.required);
        expect(getMandatoryFields(state, version), `${state} v${version}`).toEqual(shown);
      }
    }
  });
});

describe("strict mode blocks jurisdiction advisories", () => {
  const fields = getFieldsForStateAndVersion("TN", "09");
  // TN's rule pack wants 7-9 digits; this is neither, so it is a warning.
  const offending = formFor("TN", { DAQ: "ZZZZZZZZZ", DCF: "1234567890", DAI: "NASHVILLE" });

  it("surfaces the advisory in the validation report", () => {
    const issue = getValidationIssues(fields, offending, "TN", false).find((i) => i.code === "DAQ");
    expect(issue?.severity).toBe("warning");
  });

  it("refuses to generate under strict mode", () => {
    // Strict mode is documented as treating warnings as errors, and cross-field
    // warnings did block — but per-field rule packs were never consulted at
    // generation time, so the payload was built anyway.
    expect(() => generateAAMVAPayload("TN", "09", fields, offending, { strictMode: true })).toThrow(
      /jurisdiction advisories/i
    );
  });

  it("still generates with strict mode off", () => {
    expect(() =>
      generateAAMVAPayload("TN", "09", fields, offending, { strictMode: false })
    ).not.toThrow();
  });

  it("promotes the advisory to an error in the report under strict mode", () => {
    const issue = getValidationIssues(fields, offending, "TN", true).find((i) => i.code === "DAQ");
    expect(issue?.severity).toBe("error");
  });
});

describe("evaluateFieldValue weighs every rule-pack constraint", () => {
  const field: AAMVAField = { code: "DAQ", label: "Customer ID Number", type: "string" };

  it("reports an error constraint even when a warning precedes it", () => {
    // The loop returned on the first failing constraint, so a warning listed
    // ahead of an error masked the error and reported ok: true.
    const original = JURISDICTION_RULE_PACKS.WY;
    (JURISDICTION_RULE_PACKS as Record<string, unknown>).WY = {
      state: "WY",
      constraints: [
        { field: "DAQ", pattern: /^[0-9]+$/, message: "advisory", severity: "warning" },
        { field: "DAQ", pattern: /^.{9,10}$/, message: "hard length rule", severity: "error" }
      ]
    };

    try {
      const result = evaluateFieldValue(field, "AB", "WY");
      expect(result.ok).toBe(false);
      expect(result.severity).toBe("error");
      expect(result.message).toBe("hard length rule");
    } finally {
      (JURISDICTION_RULE_PACKS as Record<string, unknown>).WY = original;
    }
  });
});

describe("decodePayload rejects things that are not field maps", () => {
  it("refuses a JSON array", () => {
    // Arrays are typeof "object", so one came back as a field map whose keys
    // were array indices — and the scanner loaded it straight into the form.
    expect(decodePayload("[1,2,3]").error).toBeTruthy();
    expect(decodePayload("[1,2,3]").data).toBeUndefined();
    expect(decodeAAMVA("[1,2,3]").ok).toBeUndefined();
  });

  it("still accepts a plain object", () => {
    expect(decodePayload('{"DCS":"DOE"}').data).toEqual({ DCS: "DOE" });
  });
});

describe("PreviewActions filename privacy toggle", () => {
  it("has correct aria-describedby and dynamic status text", async () => {
    const { render, screen, fireEvent } = await import("@testing-library/react");
    const React = await import("react");
    const { PreviewActions } = await import("../components/PreviewActions");

    function TestWrapper() {
      const [includeName, setIncludeName] = React.useState(false);
      return (
        <PreviewActions
          canExport={true}
          handleExportPNG={() => {}}
          handleExportSVG={() => {}}
          handleExportPDF={() => {}}
          handlePrint={() => {}}
          includeNameInExport={includeName}
          setIncludeNameInExport={setIncludeName}
          exportBasename={(prefix) => `${prefix}_CA_DL_V10`}
          canCopyImage={false}
          handleCopyImage={() => {}}
          imgCopied={false}
          handleCopyJson={() => {}}
          jsonCopied={false}
          decoded={null}
          stale={false}
          whimsy={false}
          voice={{ supported: false, speaking: false, speak: () => {}, stop: () => {} }}
        />
      );
    }

    render(<TestWrapper />);
    fireEvent.click(screen.getByText("Filename & privacy"));

    const checkbox = screen.getByRole("checkbox", {
      name: /Put the cardholder's name in export filenames/i
    });
    expect(checkbox).not.toBeChecked();
    expect(checkbox).toHaveAttribute("aria-describedby", "export-filename-preview");

    const previewSpan = screen.getByText(/Off:/i);
    expect(previewSpan).toBeInTheDocument();
    expect(previewSpan.id).toBe("export-filename-preview");
    expect(previewSpan).toHaveTextContent("Off: barcode_CA_DL_V10.png");

    fireEvent.click(checkbox);

    expect(checkbox).toBeChecked();
    expect(screen.getByText(/On:/i)).toBeInTheDocument();
    expect(screen.getByText(/On:/i)).toHaveTextContent("On: barcode_CA_DL_V10.png");
  });
});

describe("an ID card is not required to carry driving privileges", () => {
  // DCA, DCB and DCD exist to describe driving privileges. v10/v11 already drop
  // them from an ID subfile outright, per CDS Table D.3; the older editions
  // were left demanding them "pending primary-source review". A decoded Maine
  // ID card (AAMVA v09) supplied it — the card omits all three, and the
  // generator rejected it as missing mandatory fields.
  const DRIVING = ["DCA", "DCB", "DCD"];

  it("stops demanding them on an ID subfile, every edition that defines them", () => {
    for (const version of AAMVA_VERSION_KEYS) {
      const idFields = getFieldsForStateAndVersion("ME", version, "ID");
      const demanded = getMandatoryFields("ME", version, "ID").map((f) => f.code);
      for (const code of DRIVING) {
        expect(demanded, `v${version} ID demands ${code}`).not.toContain(code);
      }
      // A DL still owes all three wherever the edition defines them.
      const dlFields = getFieldsForStateAndVersion("ME", version, "DL");
      const dlDemanded = getMandatoryFields("ME", version, "DL").map((f) => f.code);
      for (const code of DRIVING) {
        if (dlFields.some((f) => f.code === code)) {
          expect(dlDemanded, `v${version} DL dropped ${code}`).toContain(code);
        }
      }
      void idFields;
    }
  });

  it("keeps them available on the editions that still define them", () => {
    // v10/v11 remove them; earlier editions must not, or Illinois's v09 ID
    // vector — which carries all three — could no longer be encoded.
    const il = getFieldsForStateAndVersion("IL", "09", "ID").map((f) => f.code);
    for (const code of DRIVING) expect(il, `IL v09 ID lost ${code}`).toContain(code);
  });

  it("builds an ID payload that omits all three", () => {
    // Illinois's own synthetic ID vector, minus the driving-privilege codes.
    const input: Record<string, string> = { ...ID_VECTOR_INPUT };
    for (const code of DRIVING) delete input[code];

    const fields = getFieldsForStateAndVersion("IL", "09", "ID");
    const out = generateAAMVAPayload("IL", "09", fields, input, { subfileType: "ID" });
    const payload = typeof out === "string" ? out : (out as { payload: string }).payload;
    for (const code of DRIVING) expect(payload).not.toContain(code);
    expect(payload).toContain(`DCS${ID_VECTOR_INPUT.DCS}`);
  });

  it("still reports nothing outstanding to the form and the validator", () => {
    // Requiredness is read off the field list by validation, the readiness
    // counts and the progress bar alike, so all of them have to agree with the
    // generator rather than each carrying their own copy of the rule.
    const input: Record<string, string> = { ...ID_VECTOR_INPUT };
    for (const code of DRIVING) delete input[code];

    const fields = getFieldsForStateAndVersion("IL", "09", "ID");
    const issues = getValidationIssues(fields, input, "IL", false);
    expect(issues.filter((i) => DRIVING.includes(i.code))).toEqual([]);
    expect(fields.filter((f) => f.required && !(input[f.code] ?? "").trim())).toEqual([]);
  });
});

describe("Maine carries DAW", () => {
  // ME was listed in AAMVA_STATE_EXCLUDED_FIELDS as excluding DAW. A decoded
  // Maine ID card carries it, and excluding the element cost the subfile its
  // code, its value and its separator.
  it("includes DAW in the Maine field list", () => {
    expect(getFieldsForStateAndVersion("ME", "09").map((f) => f.code)).toContain("DAW");
  });

  it("emits DAW in a generated Maine payload", () => {
    const fields = getFieldsForStateAndVersion("ME", "09", "ID");
    const input: Record<string, string> = { ...ID_VECTOR_INPUT, DAJ: "ME", DAW: "180" };
    for (const code of ["DCA", "DCB", "DCD"]) delete input[code];
    const out = generateAAMVAPayload("ME", "09", fields, input, { subfileType: "ID" });
    const payload = typeof out === "string" ? out : (out as { payload: string }).payload;
    expect(payload).toContain("DAW180");
  });
});
