import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { generateAAMVAPayload } from "../core/generator";
import { decodeAAMVAFormat } from "../core/decoder";
import { getFieldsForStateAndVersion } from "../core/schema";

interface Vector {
  id: string;
  state: string;
  version: string;
  subfileType: "DL" | "ID";
  description: string;
  input: Record<string, string>;
  expectedBytes: string;
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const CORPUS_DIR = resolve(__dirname, "../core/conformance/vectors");

function loadVectors(): Vector[] {
  return readdirSync(CORPUS_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(resolve(CORPUS_DIR, f), "utf8")) as Vector);
}

describe("AAMVA conformance corpus", () => {
  const vectors = loadVectors();

  it("loads at least one vector", () => {
    expect(vectors.length).toBeGreaterThan(0);
  });

  for (const v of vectors) {
    describe(v.id, () => {
      it("generator output matches expected bytes", () => {
        const fields = getFieldsForStateAndVersion(v.state, v.version);
        const payload = generateAAMVAPayload(
          v.state,
          v.version,
          fields,
          { ...v.input },
          {
            autoGenerateDiscriminator: false,
            subfileType: v.subfileType
          }
        );
        expect(payload).toBe(v.expectedBytes);
      });

      it("expected bytes round-trip cleanly through the decoder", () => {
        const decoded = decodeAAMVAFormat(v.expectedBytes);
        expect(decoded.error).toBeUndefined();
        expect(decoded.data).toBeDefined();
        expect(decoded.data?.["DAJ"]).toBe(v.state);
      });
    });
  }
});
