import { describe, it, expect } from "vitest";

import { generateAAMVAPayload } from "../core/generator";
import { decodeAAMVAFormat } from "../core/decoder";
import { getFieldsForStateAndVersion } from "../core/schema";
import { loadVectors, REAL_WORLD_TIERS } from "./support/conformanceVectors";

describe("AAMVA conformance corpus", () => {
  const vectors = loadVectors();

  it("loads at least one vector", () => {
    expect(vectors.length).toBeGreaterThan(0);
  });

  for (const v of vectors) {
    // Name the assertion for what it actually proves. Against a synthetic
    // vector, "output matches expected bytes" only says the encoder has not
    // changed — the bytes came from the encoder in the first place. Against a
    // published or issued vector, the same comparison is the real conformance
    // claim. Same code, very different evidential weight.
    const isEvidence = REAL_WORLD_TIERS.includes(v.provenance.tier);
    const claim = isEvidence
      ? `matches ${v.provenance.tier} reference bytes (conformance)`
      : "matches its own recorded baseline (regression only)";

    describe(`${v.id} [${v.provenance.tier}]`, () => {
      it(claim, () => {
        const fields = getFieldsForStateAndVersion(v.state, v.version);
        const payload = generateAAMVAPayload(
          v.state,
          v.version,
          fields,
          { ...v.input },
          {
            autoGenerateDiscriminator: false,
            subfileType: v.subfileType
          }
        );
        expect(payload).toBe(v.expectedBytes);
      });

      it("expected bytes round-trip cleanly through the decoder", () => {
        const decoded = decodeAAMVAFormat(v.expectedBytes);
        expect(decoded.error).toBeUndefined();
        expect(decoded.data).toBeDefined();
        expect(decoded.data?.["DAJ"]).toBe(v.state);
      });
    });
  }
});
