import assert from "node:assert/strict";
import { describe, test } from "vitest";
import bwipjs from "bwip-js";
import { QUICK_FILL_PRESETS } from "../core/presetData";
import { loadQuickFillPresets } from "../core/presets";
import { generateAAMVAPayload } from "../core/generator";
import { getFieldsForStateAndVersion } from "../core/schema";
import { AAMVA_STATES } from "../core/states";
import { buildSampleFill } from "../core/sampleFiller";
import { decodeAAMVA } from "../core/decoder";
import {
  PDF417_ENCODER_OPTIONS,
  PREVIEW_SCALE,
  computeExportLayout,
  getBarcodeDimensions
} from "../core/barcodeDimensions";
import { AAMVA_STATE_RULES } from "../core/validation";

/**
 * Regression suite for defects that stopped a scannable barcode being produced.
 * Every test here maps to a path a user actually takes in the UI.
 */

const EXPORT_DPI = 300;

// The exact options BarcodePreview and the PNG/SVG exports encode with, so
// these assertions guard the shipped configuration rather than a copy of it.
const BWIP_OPTIONS = PDF417_ENCODER_OPTIONS;

function renderSize(text: string, overrides: Record<string, unknown> = {}) {
  const svg = (bwipjs as unknown as { toSVG: (o: Record<string, unknown>) => string }).toSVG({
    ...BWIP_OPTIONS,
    ...overrides,
    text
  });
  const m = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  assert.ok(m, "bwip-js should emit a viewBox we can measure");
  return { width: Number(m[1]), height: Number(m[2]) };
}

describe("quick-fill preset loading", () => {
  test("the loader returns the same records the data module holds", async () => {
    const loaded = await loadQuickFillPresets();
    expect(loaded).toEqual(QUICK_FILL_PRESETS);
  });

  test("the loader memoises, so reopening the menu costs nothing", async () => {
    expect(await loadQuickFillPresets()).toBe(await loadQuickFillPresets());
  });

  test("preset ids are unique", () => {
    const ids = QUICK_FILL_PRESETS.map((p) => p.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe("quick-fill presets", () => {
  // Every preset was missing DDE/DDF/DDG — mandatory from AAMVA v04 on — so
  // loading one produced "Missing mandatory fields" instead of a barcode, even
  // though the empty preview tells the user to load a preset to see one.
  for (const preset of QUICK_FILL_PRESETS) {
    test(`${preset.id} generates a payload in strict mode`, () => {
      const schemaFields = getFieldsForStateAndVersion(preset.state, preset.version);
      const payload = generateAAMVAPayload(
        preset.state,
        preset.version,
        schemaFields,
        { ...preset.fields, DAJ: preset.state },
        { strictMode: true, subfileType: "DL", autoGenerateDiscriminator: true }
      );
      assert.ok(payload.startsWith("@\n\rANSI "), "payload must carry the AAMVA header");
      assert.ok(decodeAAMVA(payload).ok, "generated payload must decode");
    });
  }
});

describe("sample fill", () => {
  // The sample values hard-coded a California-format DAQ and a 5-year validity
  // window, so strict mode — the default — refused to build for 12 of the 55
  // jurisdictions.
  for (const stateCode of Object.keys(AAMVA_STATES)) {
    test(`${stateCode} sample fill generates in strict mode`, () => {
      const version = AAMVA_STATES[stateCode]!.aamvaVersion;
      const schemaFields = getFieldsForStateAndVersion(stateCode, version);
      const data = buildSampleFill(schemaFields, stateCode);
      const payload = generateAAMVAPayload(stateCode, version, schemaFields, data, {
        strictMode: true,
        subfileType: "DL",
        autoGenerateDiscriminator: true
      });
      assert.ok(payload.length > 31, "payload must contain a subfile");
    });
  }

  test("sample DAQ satisfies a jurisdiction's own validator", () => {
    for (const stateCode of ["CA", "FL", "NY", "TX"]) {
      const version = AAMVA_STATES[stateCode]!.aamvaVersion;
      const fields = getFieldsForStateAndVersion(stateCode, version);
      const validator = AAMVA_STATE_RULES[stateCode]?.validators?.DAQ;
      assert.ok(validator, `${stateCode} should have a DAQ validator`);
      const daq = buildSampleFill(fields, stateCode).DAQ!;
      assert.ok(validator(daq), `${stateCode} sample DAQ "${daq}" must pass its own validator`);
    }
  });
});

describe("scan / import round-trip", () => {
  // AAMVA space-fills DAK to 11 characters. The decoder kept that padding, so
  // re-generating from a scanned or imported payload failed postal-code
  // validation and no barcode could be produced.
  for (const zip of ["94110", "941101234"]) {
    test(`a payload with DAK "${zip}" regenerates after decoding`, () => {
      const schemaFields = getFieldsForStateAndVersion("CA", "10");
      const source: Record<string, string> = {
        DCA: "C",
        DCB: "NONE",
        DCD: "NONE",
        DBA: "01012029",
        DCS: "DOE",
        DAC: "JANE",
        DAD: "Q",
        DBD: "01012025",
        DBB: "02151990",
        DBC: "2",
        DAY: "BRO",
        DAU: "067 IN",
        DAG: "123 SAMPLE ST",
        DAI: "SAN FRANCISCO",
        DAJ: "CA",
        DAK: zip,
        DAQ: "D1234567",
        DCF: "SAMPLEDD12345",
        DCG: "USA",
        DDE: "N",
        DDF: "N",
        DDG: "N"
      };
      const payload = generateAAMVAPayload(
        "CA",
        "10",
        schemaFields,
        { ...source },
        {
          strictMode: false,
          subfileType: "DL"
        }
      );

      const decoded = decodeAAMVA(payload);
      assert.ok(decoded.ok && decoded.json, "payload must decode");
      assert.equal(decoded.json!.DAK, zip, "decoded DAK must not keep its space padding");

      // WebcamScanner / JSON import feed the decoded object straight back in.
      const { state: _s, version: _v, ...reloaded } = decoded.json!;
      void _s;
      void _v;
      const again = generateAAMVAPayload(
        "CA",
        "10",
        schemaFields,
        { ...reloaded },
        {
          strictMode: false,
          subfileType: "DL"
        }
      );
      assert.equal(again, payload, "regenerating a decoded payload must reproduce it exactly");
    });
  }

  test("padded and untrimmed field values are normalised before validation", () => {
    const schemaFields = getFieldsForStateAndVersion("CA", "10");
    const payload = generateAAMVAPayload(
      "CA",
      "10",
      schemaFields,
      {
        DCA: "C",
        DCB: "NONE",
        DCD: "NONE",
        DBA: "01012029",
        DCS: "  DOE  ",
        DAC: "JANE",
        DAD: "Q",
        DBD: "01012025",
        DBB: "02151990",
        DBC: "2",
        DAY: "BRO",
        DAU: "067 IN",
        DAG: "123 SAMPLE ST",
        DAI: "SAN FRANCISCO",
        DAJ: "ca",
        DAK: "94110      ",
        DAQ: "D1234567",
        DCF: "SAMPLEDD12345",
        DCG: "USA",
        DDE: "N",
        DDF: "N",
        DDG: "N"
      },
      { strictMode: true, subfileType: "DL" }
    );
    assert.ok(payload.includes("DCSDOE\n"), "leading/trailing whitespace must be stripped");
  });

  test("a whitespace-only required field counts as missing", () => {
    const schemaFields = getFieldsForStateAndVersion("CA", "10");
    assert.throws(
      () =>
        generateAAMVAPayload(
          "CA",
          "10",
          schemaFields,
          {
            DCA: "C",
            DCB: "NONE",
            DCD: "NONE",
            DBA: "01012029",
            DCS: "   ",
            DAC: "JANE",
            DAD: "Q",
            DBD: "01012025",
            DBB: "02151990",
            DBC: "2",
            DAY: "BRO",
            DAU: "067 IN",
            DAG: "123 SAMPLE ST",
            DAI: "SAN FRANCISCO",
            DAJ: "CA",
            DAK: "94110",
            DAQ: "D1234567",
            DCF: "SAMPLEDD12345",
            DCG: "USA",
            DDE: "N",
            DDF: "N",
            DDG: "N"
          },
          { strictMode: false, subfileType: "DL" }
        ),
      /Missing mandatory fields/
    );
  });
});

describe("auto-generated card revision date", () => {
  // With an issue date earlier than the selected version's era, the generated
  // DDB landed *after* the issue date; strict mode treats that warning as
  // blocking, so the app refused to build its own auto-filled form.
  for (const issueDate of ["01012024", "01012015", "01012008"]) {
    test(`issue date ${issueDate} still generates in strict mode`, () => {
      const schemaFields = getFieldsForStateAndVersion("AZ", "10");
      // AZ caps validity at 50 years, isolating this from the validity check.
      const data: Record<string, string> = {
        DCA: "C",
        DCB: "NONE",
        DCD: "NONE",
        DBA: "01012029",
        DCS: "DOE",
        DAC: "JANE",
        DAD: "Q",
        DBD: issueDate,
        DBB: "02151990",
        DBC: "2",
        DAY: "BRO",
        DAU: "067 IN",
        DAG: "123 SAMPLE ST",
        DAI: "PHOENIX",
        DAJ: "AZ",
        DAK: "85001",
        // Supplied, not auto-generated: DAQ is the holder's licence number and
        // the generator will not invent one. DCF/DDB still come from the flag.
        DAQ: "D12345678",
        DCG: "USA",
        DDE: "N",
        DDF: "N",
        DDG: "N"
      };
      const payload = generateAAMVAPayload("AZ", "10", schemaFields, data, {
        strictMode: true,
        subfileType: "DL",
        autoGenerateDiscriminator: true
      });

      // Read the auto-filled value back out of the payload: the generator works
      // on a copy and no longer writes into the caller's object.
      const ddb = decodeAAMVA(payload).json?.DDB;
      assert.ok(ddb, "DDB should have been auto-generated");
      assert.equal(data.DDB, undefined, "the caller's object must not be mutated");
      assert.ok(
        Number(ddb.substring(4)) <= Number(issueDate.substring(4)),
        `auto DDB (${ddb}) must not postdate the issue date (${issueDate})`
      );
    });
  }
});

describe("symbol geometry", () => {
  const schemaFields = getFieldsForStateAndVersion("CA", "10");
  const buildPayload = (overrides: Record<string, string> = {}) =>
    generateAAMVAPayload(
      "CA",
      "10",
      schemaFields,
      { ...buildSampleFill(schemaFields, "CA"), ...overrides },
      { strictMode: false, subfileType: "DL", autoGenerateDiscriminator: true }
    );

  test("the symbol is wider than it is tall, like the credential's barcode area", () => {
    const { width, height } = renderSize(buildPayload());
    assert.ok(
      width / height > 1.5,
      `expected a landscape symbol, got ${width}x${height} (aspect ${(width / height).toFixed(2)})`
    );
  });

  test("a fully populated payload still encodes", () => {
    // Pinning a low column count capped the symbol at ~717 bytes; a v10 payload
    // with every field at its limit is around 500 and jurisdiction subfiles push
    // real-world payloads past that.
    const long = buildPayload({
      DCS: "A".repeat(40),
      DAC: "B".repeat(40),
      DAD: "C".repeat(40),
      DAG: "D".repeat(35),
      DAH: "E".repeat(35),
      DAI: "F".repeat(20),
      DCF: "G".repeat(25)
    });
    assert.ok(long.length > 400, `expected a large payload, got ${long.length} bytes`);
    const { width, height } = renderSize(long);
    assert.ok(width > 0 && height > 0, "a large payload must still render");
  });

  test("PNG export scales both axes by the same integer factor", () => {
    const { width, height } = renderSize(buildPayload());
    const { widthInches, heightInches } = getBarcodeDimensions("CA");
    const layout = computeExportLayout(
      width / PREVIEW_SCALE,
      height / PREVIEW_SCALE,
      Math.round(widthInches * EXPORT_DPI),
      Math.round(heightInches * EXPORT_DPI)
    );

    assert.equal(layout.scale, Math.floor(layout.scale), "scale must be a whole number of pixels");
    assert.ok(layout.scale >= 1, "scale must be at least one pixel per module");
    // Identical scale on both axes keeps modules square and preserves the
    // row-height : X-dimension ratio the symbology depends on.
    assert.equal(
      layout.drawWidth / (width / PREVIEW_SCALE),
      layout.drawHeight / (height / PREVIEW_SCALE),
      "horizontal and vertical scale factors must match"
    );
    assert.ok(
      layout.drawWidth <= Math.round(widthInches * EXPORT_DPI) &&
        layout.drawHeight <= Math.round(heightInches * EXPORT_DPI),
      "the symbol must fit inside the credential's barcode area"
    );
    assert.ok(
      layout.offsetX >= 0 && layout.offsetY >= 0,
      "the symbol must be centred, not clipped"
    );
  });

  test("the printed symbol keeps PDF417's 3:1 row-height to X-dimension ratio", () => {
    // The old export stretched each axis independently to fill the credential's
    // barcode area. That drove the ratio down to ~1.02:1, well under the 3:1
    // minimum ISO/IEC 15438 sets for PDF417.
    const sym = (
      bwipjs as unknown as {
        raw: (o: Record<string, unknown>) => Array<{ pixx: number; pixy: number }>;
      }
    ).raw({ ...BWIP_OPTIONS, text: buildPayload() })[0]!;

    const QUIET = 2;
    const { widthInches, heightInches } = getBarcodeDimensions("CA");
    const layout = computeExportLayout(
      sym.pixx + QUIET * 2,
      sym.pixy + QUIET * 2,
      Math.round(widthInches * EXPORT_DPI),
      Math.round(heightInches * EXPORT_DPI)
    );

    // bwip-js bakes a 3-module row height into the raw matrix, so one scale
    // factor across both axes preserves the ratio exactly.
    const xDimension = layout.scale;
    const rowHeight = layout.scale * 3;
    assert.ok(
      rowHeight / xDimension >= 3,
      `row height ${rowHeight}px : X-dimension ${xDimension}px is below the 3:1 minimum`
    );
  });

  test("computeExportLayout centres the symbol and tolerates a degenerate size", () => {
    const layout = computeExportLayout(100, 40, 900, 300);
    assert.equal(layout.scale, 7); // min(9, 7.5) floored
    assert.equal(layout.drawWidth, 700);
    assert.equal(layout.drawHeight, 280);
    assert.equal(layout.offsetX, 100);
    assert.equal(layout.offsetY, 10);

    const empty = computeExportLayout(0, 0, 900, 300);
    assert.equal(empty.drawWidth, 0);
    assert.equal(empty.scale, 1);
  });
});
