import { describe, expect, test } from "vitest";

import { formatInspection, inspectPayload, summarizeAnomalies } from "../core/inspect";
import { generateAAMVAPayload } from "../core/generator";
import { useFormStore } from "../hooks/useFormStore";
import { getFieldsForStateAndVersion } from "../core/schema";

const CT_RECORD: Record<string, string> = {
  DAQ: "123456789",
  DCS: "SPECIMEN",
  DDE: "N",
  DAC: "AVERY",
  DDF: "N",
  DAD: "X",
  DDG: "N",
  DCA: "D",
  DCB: "B",
  DCD: "NONE",
  DBD: "01012024",
  DBB: "01011990",
  DBA: "01012030",
  DBC: "1",
  DAU: "069 IN",
  DAY: "HAZ",
  DAG: "100 EXAMPLE RD",
  DAI: "TESTVILLE",
  DAJ: "CT",
  DCF: "24010100000001A00B",
  DAK: "060000000",
  DCG: "USA",
  DCK: "123456789CT0ABC00",
  DDA: "N",
  DDB: "02102017"
};

const generateCT = (record: Record<string, string>): string =>
  generateAAMVAPayload("CT", "09", getFieldsForStateAndVersion("CT", "09"), record, {
    autoGenerateDiscriminator: false
  });

describe("payload inspection", () => {
  test("a payload we generated balances to the byte", () => {
    const result = inspectPayload(generateCT({ ...CT_RECORD, ZCB: "0000000000" }));

    expect(result.ok).toBe(true);
    const inspection = result.inspection!;
    expect(inspection.subfiles.map((s) => s.type)).toEqual(["DL", "ZC"]);
    for (const subfile of inspection.subfiles) {
      expect(subfile.unaccountedBytes, `${subfile.type} should balance`).toBe(0);
      expect(subfile.unparsed).toEqual([]);
      expect(subfile.accountedBytes).toBe(subfile.declaredLength);
    }
    expect(inspection.totalUnaccounted).toBe(0);
    expect(summarizeAnomalies(inspection)).toBeNull();
  });

  test("reads the header the way the header is laid out", () => {
    const inspection = inspectPayload(generateCT(CT_RECORD)).inspection!;

    expect(inspection.iin).toBe("636006");
    expect(inspection.state).toBe("CT");
    expect(inspection.version).toBe("09");
    expect(inspection.jurisdictionVersion).toBe("00");
    expect(inspection.declaredEntries).toBe(1);
  });

  test("reports the jurisdiction version a profile overrides", () => {
    const ny = generateAAMVAPayload(
      "NY",
      "10",
      getFieldsForStateAndVersion("NY", "10"),
      { ...CT_RECORD, DAJ: "NY", DAU: "603", DAK: "100010000", DCK: "", DDD: "0" },
      { autoGenerateDiscriminator: false }
    );

    expect(inspectPayload(ny).inspection!.jurisdictionVersion).toBe("04");
  });

  test("names the fixed-width padding the decoder strips", () => {
    // NY pads DAK to its fixed 11-character width; the decoded value hides that,
    // which is exactly the ambiguity this exists to remove.
    const ny = generateAAMVAPayload(
      "NY",
      "10",
      getFieldsForStateAndVersion("NY", "10"),
      { ...CT_RECORD, DAJ: "NY", DAK: "10001" },
      { autoGenerateDiscriminator: false }
    );
    const inspection = inspectPayload(ny).inspection!;
    const dak = inspection.elements.find((e) => e.code === "DAK")!;

    expect(dak.raw).toBe("10001      ");
    expect(dak.value).toBe("10001");
    expect(dak.padding).toBe(6);
    expect(inspection.paddedCodes).toContain("DAK");
    expect(summarizeAnomalies(inspection)).toContain("space-filled");
  });

  test("CT's unpadded postal code reports no padding at all", () => {
    const inspection = inspectPayload(generateCT(CT_RECORD)).inspection!;
    const dak = inspection.elements.find((e) => e.code === "DAK")!;

    expect(dak.padding).toBe(0);
    expect(inspection.paddedCodes).not.toContain("DAK");
  });

  test("flags elements this build's field table does not define", () => {
    // DDH ("under 18 until") is a real AAMVA element this build has no entry
    // for. Splicing one in is how a card carrying it would read.
    const base = generateCT(CT_RECORD);
    const spliced = base.replace("DDB02102017\n", "DDB02102017\nDDH01012008\n");
    const relengthed =
      spliced.substring(0, 27) +
      String(parseInt(spliced.substring(27, 31), 10) + 12).padStart(4, "0") +
      spliced.substring(31);

    const inspection = inspectPayload(relengthed).inspection!;
    expect(inspection.unknownCodes).toEqual(["DDH"]);
    expect(inspection.subfiles[0]!.unaccountedBytes).toBe(0);
    expect(inspection.elements.find((e) => e.code === "DDH")!.value).toBe("01012008");
    expect(summarizeAnomalies(inspection)).toContain("outside the field table");
  });

  test("jurisdiction Z* elements are not reported as unknown", () => {
    // AAMVA reserves Z* to the issuer and defines nothing inside, so "absent
    // from the field table" is their normal condition, not a finding.
    const inspection = inspectPayload(generateCT({ ...CT_RECORD, ZCB: "0000000000" })).inspection!;

    expect(inspection.elements.some((e) => e.code === "ZCB")).toBe(true);
    expect(inspection.unknownCodes).toEqual([]);
  });

  test("counts declared bytes that no element explains", () => {
    // The New York case in miniature: a subfile that declares more than its
    // elements consume. A field dump cannot show this; the ledger is the point.
    const base = generateCT(CT_RECORD);
    const overstated =
      base.substring(0, 27) +
      String(parseInt(base.substring(27, 31), 10) + 99).padStart(4, "0") +
      base.substring(31);

    const inspection = inspectPayload(overstated).inspection!;
    expect(inspection.subfiles[0]!.unaccountedBytes).toBe(99);
    expect(inspection.totalUnaccounted).toBe(99);
    expect(summarizeAnomalies(inspection)).toContain("99 bytes declared but unaccounted for");
  });

  test("counts a final element terminated by CR alone", () => {
    // New York ends the last element of a subfile with the segment terminator
    // and no separator before it. Reading that tail as leftovers dropped one
    // whole element per subfile — 5 bytes for the DL subfile's DDD and 94 for
    // the ZN subfile's ZNB on a real card.
    const base = generateCT(CT_RECORD);
    const nyStyle = base.replace(/\n\r$/, "\r");

    const inspection = inspectPayload(nyStyle).inspection!;
    expect(inspection.subfiles[0]!.unaccountedBytes).toBe(1);
    expect(inspection.subfiles[0]!.unparsed).toEqual([]);
    // The last element is still read, padding stripped, like any other.
    expect(inspection.elements.at(-1)!.code).toBe("DDB");
    expect(inspection.elements.at(-1)!.value).toBe("02102017");
  });

  test("a CR-terminated final element in a jurisdiction subfile is read too", () => {
    const base = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const nyStyle = base.replace(/\n\r$/, "\r");

    const inspection = inspectPayload(nyStyle).inspection!;
    const zc = inspection.subfiles.find((s) => s.type === "ZC")!;
    expect(zc.unparsed).toEqual([]);
    expect(inspection.elements.find((e) => e.code === "ZCB")!.value).toBe("0000000000");
  });

  test("genuine leftovers are still reported as unparsed", () => {
    // The fix must not turn every tail into an element: bytes that are not a
    // valid code are still unexplained, and saying otherwise would hide damage.
    const base = generateCT(CT_RECORD);
    const garbled = base.replace(/\n\r$/, "\n!!garbage\r");
    const relengthed =
      garbled.substring(0, 27) +
      String(parseInt(garbled.substring(27, 31), 10) + 9).padStart(4, "0") +
      garbled.substring(31);

    const inspection = inspectPayload(relengthed).inspection!;
    expect(inspection.subfiles[0]!.unparsed).toEqual(["!!garbage\r"]);
  });

  test("surfaces the CT directory drift as a repaired offset", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const dlLength = parseInt(payload.substring(27, 31), 10);
    const zcOffset = parseInt(payload.substring(33, 37), 10);
    const drifted =
      payload.substring(0, 27) +
      String(dlLength + 1).padStart(4, "0") +
      payload.substring(31, 33) +
      String(zcOffset + 1).padStart(4, "0") +
      payload.substring(37);

    const inspection = inspectPayload(drifted).inspection!;
    expect(inspection.subfiles.some((s) => s.repaired)).toBe(true);
    expect(summarizeAnomalies(inspection)).toContain("repair");
  });

  test("rejects input that is not an AAMVA payload", () => {
    expect(inspectPayload("").ok).toBe(false);
    expect(inspectPayload('{"DCS":"DOE"}').error).toBe("Not an AAMVA payload");
    expect(inspectPayload("@\n\x1e\rANSI 6360").error).toBe(
      "Payload too short for an AAMVA header"
    );
  });

  test("formats a ledger that names the numbers it is reporting", () => {
    const text = formatInspection(
      inspectPayload(generateCT({ ...CT_RECORD, ZCB: "0000000000" })).inspection!
    );

    expect(text).toContain("636006 (CT)");
    expect(text).toContain("AAMVA v09, jurisdiction version 00");
    expect(text).toContain("2 directory entries");
    expect(text).toMatch(/DL {2}offset 41 {2}declared \d+B/);
    expect(text).toContain("balanced");
  });
});

describe("source payload retention", () => {
  test("a scan's raw bytes are held so the ledger can inspect the card", () => {
    const card = generateCT(CT_RECORD);
    useFormStore.getState().loadJson({ state: "CT", version: "09", DCS: "SPECIMEN" }, card);

    expect(useFormStore.getState().sourcePayload).toBe(card);
  });

  test("a preset or JSON import leaves no source attached", () => {
    const card = generateCT(CT_RECORD);
    useFormStore.getState().loadJson({ state: "CT", version: "09" }, card);
    // No second argument: there is no card behind these values, and a stale
    // payload would have the ledger describe the wrong one.
    useFormStore.getState().loadJson({ state: "CA", version: "10", DCS: "DOE" });

    expect(useFormStore.getState().sourcePayload).toBeNull();
  });

  test("clearing the form drops it — it is card data", () => {
    useFormStore.getState().loadJson({ state: "CT", version: "09" }, generateCT(CT_RECORD));
    useFormStore.getState().clearFields();

    expect(useFormStore.getState().sourcePayload).toBeNull();
  });

  test("it is never written to storage", () => {
    // `partialize` is an allow-list of UI preferences. Card bytes are PII and
    // this project does not put PII on disk.
    useFormStore.getState().loadJson({ state: "CT", version: "09" }, generateCT(CT_RECORD));

    const persisted = window.localStorage.getItem("aamva_form_prefs_v2");
    expect(persisted ?? "").not.toContain("sourcePayload");
    expect(persisted ?? "").not.toContain("SPECIMEN");
  });
});
