import { describe, expect, test } from "vitest";

import { generateAAMVAPayload, generateStateDiscriminator } from "../core/generator";
import { decodeAAMVAFormat, validateAAMVAPayloadStructure } from "../core/decoder";
import { getFieldsForStateAndVersion } from "../core/schema";
import {
  getJurisdictionEncoding,
  getJurisdictionSubfileElements,
  shouldPadPostalCode
} from "../core/jurisdictionRules";
import { getCanonicalRewrite, getQuickFix } from "../core/quickFix";

/**
 * Everything here traces back to one decoded Connecticut credential. Before it,
 * this app assumed every AAMVA payload was a single DL subfile at a fixed
 * offset with a space-filled postal code — an assumption no CT card meets.
 */
const CT_RECORD: Record<string, string> = {
  DAQ: "123456789",
  DCS: "SPECIMEN",
  DDE: "N",
  DAC: "AVERY",
  DDF: "N",
  DAD: "X",
  DDG: "N",
  DCA: "D",
  DCB: "B",
  DCD: "NONE",
  DBD: "01012024",
  DBB: "01011990",
  DBA: "01012030",
  DBC: "1",
  DAU: "069 IN",
  DAY: "HAZ",
  DAG: "100 EXAMPLE RD",
  DAI: "TESTVILLE",
  DAJ: "CT",
  DAK: "060000000",
  DCF: "24010100000001A00B",
  DCG: "USA",
  DCK: "123456789CT0ABC00",
  DDA: "N",
  DDB: "02102017"
};

function generateCT(record: Record<string, string>): string {
  return generateAAMVAPayload("CT", "09", getFieldsForStateAndVersion("CT", "09"), record, {
    autoGenerateDiscriminator: false
  });
}

/** Directory entries as `[type, offset, length]`, read straight off the wire. */
function readDirectory(payload: string): Array<[string, number, number]> {
  const count = parseInt(payload.substring(19, 21), 10);
  const entries: Array<[string, number, number]> = [];
  for (let i = 0; i < count; i++) {
    const base = 21 + i * 10;
    entries.push([
      payload.substring(base, base + 2),
      parseInt(payload.substring(base + 2, base + 6), 10),
      parseInt(payload.substring(base + 6, base + 10), 10)
    ]);
  }
  return entries;
}

describe("jurisdiction subfiles", () => {
  test("CT declares a second directory entry when the ZC subfile carries a value", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });

    expect(payload.substring(19, 21)).toBe("02");
    const [dl, zc] = readDirectory(payload);
    expect(dl?.[0]).toBe("DL");
    expect(zc?.[0]).toBe("ZC");
    // The directory is 10 bytes per entry, so two entries push the first
    // subfile from the long-assumed 31 to 41 — which is where the real card
    // puts it too.
    expect(dl?.[1]).toBe(41);
  });

  test("directory offsets and lengths land exactly on subfile boundaries", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const entries = readDirectory(payload);

    let cursor = 21 + entries.length * 10;
    for (const [type, offset, length] of entries) {
      expect(offset).toBe(cursor);
      expect(payload.substring(offset, offset + 2)).toBe(type);
      cursor += length;
    }
    // No slack at the end either: the last subfile ends where the payload does.
    expect(cursor).toBe(payload.length);
  });

  test("a jurisdiction subfile with nothing in it is not emitted", () => {
    const payload = generateCT(CT_RECORD);

    expect(payload.substring(19, 21)).toBe("01");
    expect(payload).not.toContain("ZC");
    // Back to the single-entry layout, offset and all.
    expect(readDirectory(payload)[0]?.[1]).toBe(31);
  });

  test("jurisdiction elements never leak into the DL subfile", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const [dl] = readDirectory(payload);
    const dlBytes = payload.substring(dl![1], dl![1] + dl![2]);

    expect(dlBytes).not.toContain("ZCB");
    expect(payload).toContain("ZCB0000000000");
  });

  test("the ZC subfile survives a decode round-trip", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const decoded = decodeAAMVAFormat(payload);

    expect(decoded.error).toBeUndefined();
    expect(decoded.subfiles).toEqual(["DL", "ZC"]);
    // The decoder used to read only the first subfile, so a scanned CT card
    // lost its ZC elements silently and re-encoding dropped them for good.
    expect(decoded.data?.ZCB).toBe("0000000000");
    expect(decoded.data?.DCK).toBe("123456789CT0ABC00");
  });

  test("re-encoding a decoded payload reproduces it byte for byte", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const decoded = decodeAAMVAFormat(payload);
    const reencoded = generateCT(decoded.data as Record<string, string>);

    expect(reencoded).toBe(payload);
  });

  test("a multi-subfile payload passes structural validation, strict included", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });

    expect(validateAAMVAPayloadStructure(payload)).toEqual({ ok: true });
    expect(validateAAMVAPayloadStructure(payload, true)).toEqual({ ok: true });
  });

  test("reads a card whose directory overstates the DL subfile by a byte", () => {
    // Exactly the anomaly on the source credential: it declares DL as 251
    // bytes where it holds 250, so its declared ZC offset (292) lands one byte
    // past where ZC actually starts. Both subfiles are intact and the total
    // length is right — only the boundary is wrong. Rejecting the card over two
    // digits would fail the one jurisdiction we have real evidence from.
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const [dl, zc] = readDirectory(payload);
    const drifted =
      payload.substring(0, 27) +
      String(dl![2] + 1).padStart(4, "0") +
      payload.substring(31, 33) +
      String(zc![1] + 1).padStart(4, "0") +
      payload.substring(37);

    expect(drifted).toHaveLength(payload.length);
    const decoded = decodeAAMVAFormat(drifted);
    expect(decoded.error).toBeUndefined();
    expect(decoded.subfiles).toEqual(["DL", "ZC"]);
    expect(decoded.data?.ZCB).toBe("0000000000");
    expect(decoded.data?.DCS).toBe("SPECIMEN");
    // The overlap the drift creates is trimmed, so the ZC bytes are not also
    // read as the tail of the DL subfile.
    expect(decoded.data?.DDB).toBe("02102017");
  });

  test("strict validation still refuses arithmetic it produced itself", () => {
    // The tolerance is for other people's encoders. Our own output has no
    // excuse, and strict mode is where the generator self-checks.
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const [dl] = readDirectory(payload);
    const drifted =
      payload.substring(0, 27) + String(dl![2] + 1).padStart(4, "0") + payload.substring(31);

    expect(validateAAMVAPayloadStructure(drifted, true).ok).toBe(false);
    expect(validateAAMVAPayloadStructure(drifted).ok).toBe(true);
  });

  test("a length overrun too large to be drift is still an error", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    const broken = payload.substring(0, 27) + "9999" + payload.substring(31);

    expect(validateAAMVAPayloadStructure(broken).ok).toBe(false);
    expect(decodeAAMVAFormat(broken).error).toBeTruthy();
  });

  test("a directory entry pointing at bytes that are not its subfile is rejected", () => {
    const payload = generateCT({ ...CT_RECORD, ZCB: "0000000000" });
    // Push the ZC offset far enough that the nudge cannot rescue it.
    const broken = payload.substring(0, 33) + "0500" + payload.substring(37);

    expect(validateAAMVAPayloadStructure(broken).ok).toBe(false);
  });

  test("a jurisdiction nobody has decoded a card from keeps the spec defaults", () => {
    // Profiles are opt-in: one decoded card must not quietly rewrite the
    // encoding for the 52 jurisdictions it says nothing about.
    expect(getJurisdictionEncoding("TX")).toBeUndefined();
    expect(getJurisdictionSubfileElements("TX")).toEqual([]);
    expect(shouldPadPostalCode("TX")).toBe(true);

    const tx = generateAAMVAPayload(
      "TX",
      "10",
      getFieldsForStateAndVersion("TX", "10"),
      { ...CT_RECORD, DAJ: "TX", DAQ: "12345678", ZCB: "0000000000" },
      { autoGenerateDiscriminator: false }
    );
    expect(tx.substring(19, 21)).toBe("01");
    expect(tx).not.toContain("ZCB");
    // Jurisdiction version stays "00" where no card has said otherwise.
    expect(tx.substring(17, 19)).toBe("00");
  });

  test("CT's ZC elements do not appear on NY, and NY's ZN elements not on CT", () => {
    const ctCodes = getJurisdictionSubfileElements("CT").map((e) => e.code);
    const nyCodes = getJurisdictionSubfileElements("NY").map((e) => e.code);

    expect(ctCodes).toEqual(["ZCA", "ZCB"]);
    expect(nyCodes).toEqual(["ZNA", "ZNB"]);
    expect(getFieldsForStateAndVersion("CT", "09").map((f) => f.code)).not.toContain("ZNA");
    expect(getFieldsForStateAndVersion("NY", "10").map((f) => f.code)).not.toContain("ZCA");
  });
});

describe("CT encoding profile", () => {
  test("DAK is emitted as a bare ZIP, not space-filled to 11", () => {
    const payload = generateCT(CT_RECORD);

    expect(payload).toContain("DAK060000000\n");
    expect(payload).not.toContain("DAK060000000  ");
    expect(shouldPadPostalCode("CT")).toBe(false);
  });

  test("other jurisdictions still pad DAK to its fixed 11-character width", () => {
    const payload = generateAAMVAPayload(
      "NY",
      "09",
      getFieldsForStateAndVersion("NY", "09"),
      { ...CT_RECORD, DAJ: "NY", DAK: "10001" },
      { autoGenerateDiscriminator: false }
    );

    expect(payload).toMatch(/DAK10001 {6}\n/);
  });

  test("elements are written in the order the card writes them", () => {
    const payload = generateCT(CT_RECORD);
    const order = [...payload.matchAll(/\n([A-Z]{2}[A-Z0-9])/g)].map((m) => m[1]);

    expect(order).toEqual([
      "DCS",
      "DDE",
      "DAC",
      "DDF",
      "DAD",
      "DDG",
      "DCA",
      "DCB",
      "DCD",
      "DBD",
      "DBB",
      "DBA",
      "DBC",
      "DAU",
      "DAY",
      "DAG",
      "DAI",
      "DAJ",
      "DAK",
      "DCF",
      "DCG",
      "DCK",
      "DDA",
      "DDB"
    ]);
    // DAQ opens the subfile, so it has no leading separator to match on.
    expect(payload).toContain("DLDAQ123456789\n");
  });

  test("an element outside the recorded order still gets written", () => {
    // DAH is absent from the CT order list. Dropping unlisted codes would mean
    // a schema addition silently vanishing from the payload.
    const payload = generateCT({ ...CT_RECORD, DAH: "APT 4" });

    expect(payload).toContain("DAHAPT 4\n");
  });

  test("the document discriminator opens with the issue date, as CT's does", () => {
    const dcf = generateStateDiscriminator("CT", "11162025");

    expect(dcf).toHaveLength(18);
    expect(dcf.startsWith("251116")).toBe(true);
    expect(dcf).toMatch(/^\d{14}[A-Z]\d{2}[A-Z]$/);
  });

  test("the discriminator is still well-formed with no issue date to derive from", () => {
    for (let i = 0; i < 25; i++) {
      expect(generateStateDiscriminator("CT")).toMatch(/^\d{14}[A-Z]\d{2}[A-Z]$/);
    }
  });
});

describe("NY encoding profile", () => {
  const NY_RECORD: Record<string, string> = {
    DCA: "D",
    DCB: "NONE",
    DCD: "NONE",
    DBA: "01162028",
    DCS: "SPECIMEN",
    DAC: "AVERY",
    DAD: "P",
    DBD: "12172024",
    DBB: "01161991",
    DBC: "1",
    DAY: "BRO",
    DAU: "603",
    DAG: "100 EXAMPLE AVE # 0000",
    DAI: "NEW YORK",
    DAJ: "NY",
    DAK: "100010000",
    DAQ: "123456789",
    DCF: "KMEMI7FG20",
    DCG: "USA",
    DDE: "U",
    DDF: "U",
    DDG: "U",
    DDA: "N",
    DDB: "03072022",
    DDD: "0"
  };

  const generateNY = (record: Record<string, string>): string =>
    generateAAMVAPayload("NY", "10", getFieldsForStateAndVersion("NY", "10"), record, {
      autoGenerateDiscriminator: false
    });

  test("writes the jurisdiction version the cards carry, not a hardcoded 00", () => {
    const payload = generateNY(NY_RECORD);

    // Header layout: "ANSI " + IIN(6) + AAMVA version(2) + jurisdiction version(2).
    expect(payload.substring(9, 15)).toBe("636001");
    expect(payload.substring(15, 17)).toBe("10");
    expect(payload.substring(17, 19)).toBe("04");
  });

  test("the ZN subfile keeps mixed-case values byte for byte", () => {
    // ZNB on the source card is an opaque blob of mixed-case printable ASCII.
    // The AAMVA text rule upper-cases string fields, which would silently
    // rewrite data whose meaning nobody outside the DMV knows.
    const blob = '0LZ$c>Xf2jS/?W%E;R,]\'/e*>`%\\$/$;F<OSli^u%"kOr![.QqNK"BZ2HQNU';
    const payload = generateNY({ ...NY_RECORD, ZNA: "SPECIMEN@AVERY@P", ZNB: blob });

    // ZNB is the subfile's last element, and NY closes those with the segment
    // terminator alone — no separator before it.
    expect(payload).toContain(`ZNB${blob}\r`);
    expect(decodeAAMVAFormat(payload).data?.ZNB).toBe(blob);
  });

  test("standard elements are still upper-cased", () => {
    const payload = generateNY({ ...NY_RECORD, DAI: "new york" });

    // NY space-fills DAI to 20, so the upper-cased value is followed by padding
    // rather than by the separator.
    expect(payload).toContain("DAINEW YORK            \n");
  });

  test("space-fills values to the widths the card uses", () => {
    const payload = generateNY(NY_RECORD);

    // Measured off the credential: ten elements, 100 bytes of fill. Only four
    // of these widths are the AAMVA ones.
    expect(payload).toContain("DCAD   \n");
    expect(payload).toContain("DCBNONE      \n");
    expect(payload).toContain("DCSSPECIMEN                 \n");
    expect(payload).toContain("DAU603   \n");
    expect(payload).toContain("DAK100010000  \n");
  });

  test("a value at or over its width is written unchanged", () => {
    // Padding must never truncate: DAI is width 20 and this value is exactly 20.
    const payload = generateNY({ ...NY_RECORD, DAI: "ABCDEFGHIJKLMNOPQRST" });

    expect(payload).toContain("DAIABCDEFGHIJKLMNOPQRST\n");
  });

  test("a jurisdiction with no recorded widths pads nothing but DAK", () => {
    const tx = generateAAMVAPayload(
      "TX",
      "10",
      getFieldsForStateAndVersion("TX", "10"),
      { ...NY_RECORD, DAJ: "TX", DAQ: "12345678", DAI: "AUSTIN" },
      { autoGenerateDiscriminator: false }
    );

    expect(tx).toContain("DAIAUSTIN\n");
    expect(tx).toContain("DCAD\n");
  });

  test("emits elements in schema order, which is the order the card uses", () => {
    const payload = generateNY(NY_RECORD);
    const order = [...payload.matchAll(/\n([A-Z]{2}[A-Z0-9])/g)].map((m) => m[1]);

    expect(order).toEqual([
      "DCB",
      "DCD",
      "DBA",
      "DCS",
      "DAC",
      "DAD",
      "DBD",
      "DBB",
      "DBC",
      "DAY",
      "DAU",
      "DAG",
      "DAI",
      "DAJ",
      "DAK",
      "DAQ",
      "DCF",
      "DCG",
      "DDE",
      "DDF",
      "DDG",
      "DDA",
      "DDB",
      "DDD"
    ]);
  });

  test("the document discriminator is alphanumeric, not all digits", () => {
    const seen = new Set<string>();
    for (let i = 0; i < 200; i++) seen.add(generateStateDiscriminator("NY"));

    for (const dcf of seen) expect(dcf).toMatch(/^[A-Z0-9]{10}$/);
    // Across 200 draws, an alphabet that includes letters will have produced
    // at least one. A digits-only generator passes the regex above and fails here.
    expect([...seen].some((dcf) => /[A-Z]/.test(dcf))).toBe(true);
  });

  test("DDD (limited duration indicator) is available on 08 and later only", () => {
    for (const version of ["08", "09", "10"]) {
      expect(
        getFieldsForStateAndVersion("NY", version).map((f) => f.code),
        `v${version}`
      ).toContain("DDD");
    }
    for (const version of ["03", "04"]) {
      expect(
        getFieldsForStateAndVersion("NY", version).map((f) => f.code),
        `v${version}`
      ).not.toContain("DDD");
    }
  });
});

describe("height notation", () => {
  test("leaves a feet-and-inches height alone", () => {
    // NY writes 6'3" as "603". Reading that as inches and "correcting" it to
    // "603 IN" turned a real cardholder into a fifty-foot one.
    const field = getFieldsForStateAndVersion("NY", "10").find((f) => f.code === "DAU")!;

    for (const value of ["603", "510", "411", "700"]) {
      expect(getCanonicalRewrite(field, value, "NY", false), value).toBeNull();
      expect(getQuickFix(field, value, "NY", false), value).toBeNull();
    }
  });

  test("still normalizes the notations that are genuinely ambiguous input", () => {
    const field = getFieldsForStateAndVersion("CT", "09").find((f) => f.code === "DAU")!;

    expect(getCanonicalRewrite(field, "5'9\"", "CT", false)?.value).toBe("069 IN");
    expect(getCanonicalRewrite(field, "69 in", "CT", false)?.value).toBe("069 IN");
    expect(getCanonicalRewrite(field, "175cm", "CT", false)?.value).toBe("175 CM");
    // A leading zero rules out feet-and-inches, so this is still inches.
    expect(getCanonicalRewrite(field, "069", "CT", false)?.value).toBe("069 IN");
  });
});

describe("DCK (inventory control number)", () => {
  test("is available on every version that defines it", () => {
    for (const version of ["03", "04", "08", "09", "10"]) {
      const codes = getFieldsForStateAndVersion("CT", version).map((f) => f.code);
      expect(codes, `v${version}`).toContain("DCK");
    }
  });

  test("is absent from versions predating it", () => {
    for (const version of ["01", "02"]) {
      const codes = getFieldsForStateAndVersion("CT", version).map((f) => f.code);
      expect(codes, `v${version}`).not.toContain("DCK");
    }
  });

  test("is optional — a card without one still generates", () => {
    expect(() => generateCT({ ...CT_RECORD, DCK: "" })).not.toThrow();
  });
});
