import { describe, test, expect } from "vitest";
import { validateAAMVAPayloadStructure } from "../core/decoder";
import { generateAAMVAPayload } from "../core/generator";
import { getFieldsForStateAndVersion } from "../core/schema";

// Mirror SAMPLE_BATCH from BatchProcessor so we can verify the published
// template parses, encodes, and validates end-to-end.
const SAMPLE_BATCH = [
  {
    state: "CA",
    version: "10",
    subfileType: "DL" as const,
    DCS: "DOE",
    DAC: "JANE",
    DAD: "Q",
    DBA: "01012029",
    DBB: "02151990",
    DBC: "2",
    DAY: "BRO",
    DAU: "067 IN",
    DAG: "123 SAMPLE ST",
    DAI: "SAN FRANCISCO",
    DAJ: "CA",
    DAK: "94110",
    DAQ: "D1234567",
    DCA: "C",
    DCB: "NONE",
    DCD: "NONE",
    DBD: "01012024",
    DCG: "USA",
    DDE: "N",
    DDF: "N",
    DDG: "N"
  },
  {
    state: "TX",
    version: "10",
    subfileType: "ID" as const,
    DCS: "ROE",
    DAC: "JOHN",
    DBA: "06012028",
    DBB: "07201985",
    DBC: "1",
    DAY: "BLU",
    DAU: "071 IN",
    DAG: "456 EXAMPLE AVE",
    DAI: "AUSTIN",
    DAJ: "TX",
    DAK: "78701",
    DAQ: "12345678",
    DCA: "C",
    DCB: "NONE",
    DCD: "NONE",
    DBD: "06012023",
    DCG: "USA",
    DDE: "N",
    DDF: "N",
    DDG: "N"
  }
];

describe("Phase 2 — batch template sample", () => {
  test("template entries each carry state and version", () => {
    for (const row of SAMPLE_BATCH) {
      expect(row.state.length).toBe(2);
      expect(row.version.length).toBe(2);
    }
  });

  test("template entries produce valid AAMVA payloads", () => {
    for (const row of SAMPLE_BATCH) {
      const schemaFields = getFieldsForStateAndVersion(row.state, row.version);
      const data = Object.fromEntries(Object.entries(row).map(([k, v]) => [k, v ?? ""]));
      const payload = generateAAMVAPayload(row.state, row.version, schemaFields, data, {
        strictMode: true,
        subfileType: row.subfileType,
        autoGenerateDiscriminator: true
      });
      const validation = validateAAMVAPayloadStructure(payload, true);
      expect(validation.ok, validation.errors?.join(", ")).toBe(true);
    }
  });
});
