import { describe, test, expect } from "vitest";
import { buildSampleFill, SAMPLE_FILL_VALUES } from "../core/sampleFiller";
import { getFieldsForStateAndVersion } from "../core/schema";
import { generateAAMVAPayload } from "../core/generator";
import { validateAAMVAPayloadStructure } from "../core/decoder";

describe("Phase 4 — sample filler", () => {
  test("only emits keys that exist in the schema", () => {
    const schemaFields = getFieldsForStateAndVersion("CA", "10");
    const sample = buildSampleFill(schemaFields);
    const codes = new Set(schemaFields.map((f) => f.code));
    for (const code of Object.keys(sample)) {
      expect(codes.has(code)).toBe(true);
    }
  });

  test("filled CA v10 sample passes strict-mode generation and structural validation", () => {
    const schemaFields = getFieldsForStateAndVersion("CA", "10");
    const data = buildSampleFill(schemaFields);
    const payload = generateAAMVAPayload("CA", "10", schemaFields, data, {
      strictMode: true,
      subfileType: "DL",
      autoGenerateDiscriminator: true
    });
    const result = validateAAMVAPayloadStructure(payload, true);
    expect(result.ok, result.errors?.join(", ")).toBe(true);
  });

  test("skips empty placeholder values so existing input is preserved", () => {
    expect(SAMPLE_FILL_VALUES.DAH).toBe("");
    const schemaFields = getFieldsForStateAndVersion("CA", "10");
    const sample = buildSampleFill(schemaFields);
    expect(sample.DAH).toBeUndefined();
  });
});
