import { describe, it, expect } from "vitest";

import { generateAAMVAPayload } from "../core/generator";
import { getFieldsForStateAndVersion } from "../core/schema";
import { buildSampleFill } from "../core/sampleFiller";
import { AAMVA_STATES } from "../core/states";
import { PDF417_ENCODER_OPTIONS } from "../core/barcodeDimensions";
import { loadVectors } from "./support/conformanceVectors";
import {
  describeDifference,
  encodePayloadToModules,
  rasterizeModules,
  scanPayload,
  scanRaster
} from "./support/scanOracle";

/**
 * These tests are the only ones in the suite that do not grade our encoder with
 * our own decoder. ZXing has no knowledge of `generator.ts`, so a shared wrong
 * assumption between our encode and decode paths shows up here and nowhere
 * else.
 */
describe("scan oracle: the symbol a scanner actually reads", () => {
  it("recovers a payload byte-for-byte, control characters included", () => {
    const fields = getFieldsForStateAndVersion("CA", "10");
    const payload = generateAAMVAPayload("CA", "10", fields, buildSampleFill(fields, "CA"), {
      subfileType: "DL",
      autoGenerateDiscriminator: true
    });

    const scan = scanPayload(payload);
    expect(scan.ok, `symbol did not decode: ${scan.ok ? "" : scan.error}`).toBe(true);
    if (!scan.ok) return;

    // The separators are the whole point: @ \n <RS> \r survive the barcode.
    expect(scan.text.startsWith("@\n\x1e\r")).toBe(true);
    expect(describeDifference(scan.text, payload)).toBe("identical");
    expect(scan.text).toBe(payload);
  });

  it("preserves the trailing space padding the encoder writes into DAK", () => {
    const fields = getFieldsForStateAndVersion("CA", "10");
    const payload = generateAAMVAPayload(
      "CA",
      "10",
      fields,
      { ...buildSampleFill(fields, "CA"), DAK: "94110" },
      { subfileType: "DL", autoGenerateDiscriminator: true }
    );

    // generator.ts pads DAK to 11 characters and decoder.ts strips it back off.
    // Both could be wrong together; a real reader settles what is on the card.
    expect(payload).toContain("DAK94110      \n");

    const scan = scanPayload(payload);
    expect(scan.ok).toBe(true);
    if (scan.ok) expect(scan.text).toContain("DAK94110      \n");
  });

  for (const vector of loadVectors()) {
    it(`${vector.id} survives a real PDF417 reader`, () => {
      const scan = scanPayload(vector.expectedBytes);
      expect(scan.ok, `symbol did not decode: ${scan.ok ? "" : scan.error}`).toBe(true);
      if (!scan.ok) return;
      expect(describeDifference(scan.text, vector.expectedBytes)).toBe("identical");
    });
  }
});

describe("scan oracle: every jurisdiction's strict-mode symbol", () => {
  for (const stateCode of Object.keys(AAMVA_STATES)) {
    it(`${stateCode} renders a symbol that reads back unchanged`, () => {
      const version = AAMVA_STATES[stateCode]!.aamvaVersion;
      const fields = getFieldsForStateAndVersion(stateCode, version);
      const payload = generateAAMVAPayload(
        stateCode,
        version,
        fields,
        buildSampleFill(fields, stateCode),
        { strictMode: true, subfileType: "DL", autoGenerateDiscriminator: true }
      );

      const scan = scanPayload(payload);
      expect(scan.ok, `${stateCode} symbol did not decode: ${scan.ok ? "" : scan.error}`).toBe(
        true
      );
      if (!scan.ok) return;
      expect(describeDifference(scan.text, payload)).toBe("identical");
    });
  }
});

/**
 * An oracle that cannot fail proves nothing. These assert the referee is awake:
 * if they ever pass trivially, the round-trip tests above are decoration.
 */
describe("scan oracle: negative controls", () => {
  const fields = getFieldsForStateAndVersion("CA", "10");
  const payload = generateAAMVAPayload("CA", "10", fields, buildSampleFill(fields, "CA"), {
    subfileType: "DL",
    autoGenerateDiscriminator: true
  });

  it("never reports the original payload from a heavily damaged symbol", () => {
    const matrix = encodePayloadToModules(payload);
    const modules = [...matrix.modules];
    // Erase the middle half of the symbol — far beyond what the configured
    // error correction can rebuild.
    const from = Math.floor(matrix.columns * 0.25);
    const to = Math.floor(matrix.columns * 0.75);
    for (let row = 0; row < matrix.rows; row++) {
      for (let col = from; col < to; col++) modules[row * matrix.columns + col] = 0;
    }

    const scan = scanRaster(rasterizeModules({ ...matrix, modules }));
    expect(scan.ok && scan.text === payload).toBe(false);
  });

  it("returns nothing at all for a blank field", () => {
    const matrix = encodePayloadToModules(payload);
    const scan = scanRaster(rasterizeModules({ ...matrix, modules: matrix.modules.map(() => 0) }));
    expect(scan.ok).toBe(false);
  });

  it("distinguishes two payloads that differ by one character", () => {
    const other = generateAAMVAPayload(
      "CA",
      "10",
      fields,
      { ...buildSampleFill(fields, "CA"), DAC: "JOHN" },
      { subfileType: "DL", autoGenerateDiscriminator: true }
    );
    expect(other).not.toBe(payload);

    const a = scanPayload(payload);
    const b = scanPayload(other);
    expect(a.ok && b.ok).toBe(true);
    if (a.ok && b.ok) {
      expect(a.text).not.toBe(b.text);
      expect(b.text).toContain("DACJOHN");
    }
  });

  it("still reads a symbol that has lost an entire row", () => {
    // eclevel 5 buys real damage tolerance, which is why a printed, scuffed
    // card still scans. Pinning it here means lowering `eclevel` to save space
    // has to be a deliberate decision rather than a silent one.
    const matrix = encodePayloadToModules(payload);
    const modules = [...matrix.modules];
    for (let col = 0; col < matrix.columns; col++) {
      modules[(matrix.rows - 1) * matrix.columns + col] = 0;
    }

    const scan = scanRaster(rasterizeModules({ ...matrix, modules }));
    expect(scan.ok).toBe(true);
    if (scan.ok) expect(scan.text).toBe(payload);
  });

  it("reads the app's own encoder options, so option drift is re-validated", () => {
    // If someone pins `columns` or changes `eclevel`, the oracle re-encodes with
    // the new setting rather than a copy that quietly went stale.
    expect(PDF417_ENCODER_OPTIONS.bcid).toBe("pdf417");
    const matrix = encodePayloadToModules(payload);
    // PDF417 symbol width is 17 * (dataColumns + 4) + 1 modules.
    expect((matrix.columns - 1) % 17).toBe(0);
    expect(matrix.rows).toBeGreaterThan(2);
  });
});
