import { describe, it, expect } from "vitest";
import {
  AAMVA_VERSIONS,
  AAMVA_VERSION_KEYS,
  isSupportedVersion,
  getFieldsForVersion,
  getFieldsForStateAndVersion,
  getEffectiveMaxLength
} from "../core/schema";
import { generateAAMVAPayload, generateStateCardRevisionDate } from "../core/generator";
import { decodeAAMVA } from "../core/decoder";

describe("AAMVA version 11 (Card Design Standard 2025)", () => {
  it("is in the version table and picker order after 10", () => {
    expect(isSupportedVersion("11")).toBe(true);
    expect(AAMVA_VERSIONS["11"]?.name).toMatch(/2025/);
    expect(AAMVA_VERSION_KEYS).toEqual([
      "01",
      "02",
      "03",
      "04",
      "05",
      "06",
      "07",
      "08",
      "09",
      "10",
      "11"
    ]);
  });

  it("carries DDM/DDN/DDO/DDP and not DCL", () => {
    const codes = getFieldsForVersion("11").map((f) => f.code);
    expect(codes).toEqual(expect.arrayContaining(["DDM", "DDN", "DDO", "DDP"]));
    expect(codes).not.toContain("DCL");
    expect(getFieldsForStateAndVersion("CA", "11").map((f) => f.code)).not.toContain("DCL");
  });

  it("round-trips through generate → decode with the indicators on the wire", () => {
    const state = "CA";
    const version = "11";
    const fields = getFieldsForStateAndVersion(state, version);
    const data = {
      DAQ: "D1234567",
      DCF: "ABCDEFGH1234",
      DCS: "DOE",
      DAC: "JANE",
      DBB: "01011990",
      DBA: "01012030",
      DBD: "01012024",
      DBC: "2",
      DAY: "BRO",
      DAU: "510",
      DAG: "123 MAIN ST",
      DAI: "LOS ANGELES",
      DAJ: "CA",
      DAK: "90001",
      DCG: "USA",
      DCA: "C",
      DCB: "NONE",
      DCD: "NONE",
      DDE: "N",
      DDF: "N",
      DDG: "N",
      DDM: "1",
      DDO: "1"
    };

    const payload = generateAAMVAPayload(state, version, fields, data, {
      autoGenerateDiscriminator: false
    });
    expect(payload).toContain("DDM1");
    expect(payload).toContain("DDO1");
    expect(payload).not.toContain("DCL");

    const decoded = decodeAAMVA(payload);
    expect(decoded.ok).toBe(true);
    expect(decoded.json?.DDM).toBe("1");
    expect(decoded.json?.DDO).toBe("1");
    expect(decoded.json?.version).toBe("11");
  });
});

describe("version 11 reaches the encoder, not just the validator", () => {
  // All three were caught in review on the PR: the schema said nine while the
  // form control, the wire format and the revision-date era still said ten or
  // eleven. A version that only narrows validation rejects values it then
  // encodes in the old representation anyway.
  const SAMPLE: Record<string, string> = {
    DAQ: "D1234567",
    DCF: "ABCDEFGH1234",
    DCS: "DOE",
    DAC: "JANE",
    DBB: "01011990",
    DBA: "01012030",
    DBD: "01012024",
    DBC: "2",
    DAY: "BRO",
    DAU: "510",
    DAG: "123 MAIN ST",
    DAI: "LOS ANGELES",
    DAJ: "CA",
    DCG: "USA",
    DCA: "C",
    DCB: "NONE",
    DCD: "NONE",
    DDE: "N",
    DDF: "N",
    DDG: "N"
  };
  const build = (version: string, dak: string) =>
    generateAAMVAPayload(
      "CA",
      version,
      getFieldsForStateAndVersion("CA", version),
      {
        ...SAMPLE,
        DAK: dak
      },
      { autoGenerateDiscriminator: false }
    );

  it("zero-fills DAK to nine rather than space-padding it to eleven", () => {
    const payload = build("11", "90001");
    expect(payload).toContain("DAK900010000");
    expect(payload).not.toContain("DAK90001      ");
  });

  it("writes a nine-digit ZIP unchanged", () => {
    expect(build("11", "232690000")).toContain("DAK232690000");
  });

  it("leaves version 10's padded eleven alone", () => {
    expect(build("10", "90001")).toContain("DAK90001      ");
  });

  it("caps the form control where the validator caps", () => {
    const dak = (v: string) => getFieldsForVersion(v).find((f) => f.code === "DAK")!;
    expect(getEffectiveMaxLength(dak("11"))).toBe(9);
    expect(getEffectiveMaxLength(dak("10"))).toBe(11);
  });

  it("dates a v11 card revision in the 2025 era", () => {
    // No jurisdiction defaults to 11, so without an explicit version this came
    // back in the state's own era — 2019-2024 for California.
    for (let i = 0; i < 25; i++) {
      const ddb = generateStateCardRevisionDate("CA", "06062026", "11");
      expect(ddb).toBeTruthy();
      const year = Number(ddb!.slice(4, 8));
      expect(year).toBeGreaterThanOrEqual(2025);
      expect(year).toBeLessThanOrEqual(2030);
    }
  });
});
