import { describe, it, expect } from "vitest";
import {
  AAMVA_VERSIONS,
  AAMVA_VERSION_KEYS,
  isSupportedVersion,
  getFieldsForVersion,
  getFieldsForStateAndVersion
} from "../core/schema";
import { generateAAMVAPayload } from "../core/generator";
import { decodeAAMVA } from "../core/decoder";

describe("AAMVA version 11 (Card Design Standard 2025)", () => {
  it("is in the version table and picker order after 10", () => {
    expect(isSupportedVersion("11")).toBe(true);
    expect(AAMVA_VERSIONS["11"]?.name).toMatch(/2025/);
    expect(AAMVA_VERSION_KEYS).toEqual([
      "01",
      "02",
      "03",
      "04",
      "05",
      "06",
      "07",
      "08",
      "09",
      "10",
      "11"
    ]);
  });

  it("carries DDM/DDN/DDO/DDP and not DCL", () => {
    const codes = getFieldsForVersion("11").map((f) => f.code);
    expect(codes).toEqual(expect.arrayContaining(["DDM", "DDN", "DDO", "DDP"]));
    expect(codes).not.toContain("DCL");
    expect(getFieldsForStateAndVersion("CA", "11").map((f) => f.code)).not.toContain("DCL");
  });

  it("round-trips through generate → decode with the indicators on the wire", () => {
    const state = "CA";
    const version = "11";
    const fields = getFieldsForStateAndVersion(state, version);
    const data = {
      DAQ: "D1234567",
      DCF: "ABCDEFGH1234",
      DCS: "DOE",
      DAC: "JANE",
      DBB: "01011990",
      DBA: "01012030",
      DBD: "01012024",
      DBC: "2",
      DAY: "BRO",
      DAU: "510",
      DAG: "123 MAIN ST",
      DAI: "LOS ANGELES",
      DAJ: "CA",
      DAK: "90001",
      DCG: "USA",
      DCA: "C",
      DCB: "NONE",
      DCD: "NONE",
      DDE: "N",
      DDF: "N",
      DDG: "N",
      DDM: "1",
      DDO: "1"
    };

    const payload = generateAAMVAPayload(state, version, fields, data, {
      autoGenerateDiscriminator: false
    });
    expect(payload).toContain("DDM1");
    expect(payload).toContain("DDO1");
    expect(payload).not.toContain("DCL");

    const decoded = decodeAAMVA(payload);
    expect(decoded.ok).toBe(true);
    expect(decoded.json?.DDM).toBe("1");
    expect(decoded.json?.DDO).toBe("1");
    expect(decoded.json?.version).toBe("11");
  });
});
