import { describe, expect, test } from "vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

import { PayloadInspector } from "../components/PayloadInspector";
import { generateAAMVAPayload } from "../core/generator";
import { getFieldsForStateAndVersion } from "../core/schema";

const RECORD: Record<string, string> = {
  DAQ: "123456789",
  DCS: "SPECIMEN",
  DDE: "N",
  DAC: "AVERY",
  DDF: "N",
  DAD: "X",
  DDG: "N",
  DCA: "D",
  DCB: "B",
  DCD: "NONE",
  DBD: "01012024",
  DBB: "01011990",
  DBA: "01012030",
  DBC: "1",
  DAU: "069 IN",
  DAY: "HAZ",
  DAG: "100 EXAMPLE RD",
  DAI: "TESTVILLE",
  DAJ: "CT",
  DAK: "060000000",
  DCF: "24010100000001A00B",
  DCG: "USA",
  DDA: "N",
  DDB: "02102017"
};

function renderInspector(payloadStr: string) {
  return render(
    <PayloadInspector
      payloadStr={payloadStr}
      stale={false}
      decodedEntries={[]}
      issues={[]}
      onScrollToField={() => {}}
      onCopyPayload={() => {}}
      copied={false}
    />
  );
}

const ctPayload = (record: Record<string, string>): string =>
  generateAAMVAPayload("CT", "09", getFieldsForStateAndVersion("CT", "09"), record, {
    autoGenerateDiscriminator: false
  });

describe("Wire Ledger panel", () => {
  test("reports a balanced payload without making the user open it", async () => {
    renderInspector(ctPayload({ ...RECORD, ZCB: "0000000000" }));

    const section = screen.getByRole("button", { name: /Wire Ledger/i });
    expect(section).toHaveTextContent("Balanced");

    await userEvent.click(section);
    expect(screen.getByLabelText("Subfile byte accounting")).toBeInTheDocument();
    expect(screen.getByText(/Every declared byte is accounted for/i)).toBeInTheDocument();
  });

  test("shows a row per subfile with its declared and accounted bytes", async () => {
    const payload = ctPayload({ ...RECORD, ZCB: "0000000000" });
    renderInspector(payload);
    await userEvent.click(screen.getByRole("button", { name: /Wire Ledger/i }));

    const rows = screen.getByLabelText("Subfile byte accounting").querySelectorAll("tbody tr");
    expect(rows).toHaveLength(2);
    expect(rows[0]).toHaveTextContent("DL");
    expect(rows[1]).toHaveTextContent("ZC");
    // The two-entry directory puts the first subfile at 41, not the long-assumed 31.
    expect(rows[0]).toHaveTextContent("41");
  });

  test("flags a subfile that declares more bytes than its elements explain", async () => {
    // The New York case: 99 declared bytes no element accounts for.
    const base = ctPayload(RECORD);
    const overstated =
      base.substring(0, 27) +
      String(parseInt(base.substring(27, 31), 10) + 99).padStart(4, "0") +
      base.substring(31);

    renderInspector(overstated);
    const section = screen.getByRole("button", { name: /Wire Ledger/i });
    expect(section).toHaveTextContent("Check");

    await userEvent.click(section);
    expect(screen.getByText(/99 bytes declared but unaccounted for/i)).toBeInTheDocument();
  });

  test("names the padding the decoded table hides", async () => {
    const ny = generateAAMVAPayload(
      "NY",
      "10",
      getFieldsForStateAndVersion("NY", "10"),
      { ...RECORD, DAJ: "NY", DAK: "10001" },
      { autoGenerateDiscriminator: false }
    );

    renderInspector(ny);
    await userEvent.click(screen.getByRole("button", { name: /Wire Ledger/i }));

    expect(screen.getByText(/Space-filled on the wire/i)).toBeInTheDocument();
    expect(screen.getByText(/DAK — "10001" \+ 6 spaces/)).toBeInTheDocument();
  });

  test("says so plainly when there is no payload to inspect", async () => {
    renderInspector("");
    await userEvent.click(screen.getByRole("button", { name: /Wire Ledger/i }));

    expect(screen.getByText(/Empty or invalid input/i)).toBeInTheDocument();
  });
});
