/**
 * Loader and provenance schema for the conformance corpus.
 *
 * The corpus exists to answer one question: does this implementation match what
 * DMVs actually issue? A vector can only answer that if we know where its bytes
 * came from. A vector generated by our own encoder cannot — it says "we still
 * do what we did last release", which is a regression check, not evidence of
 * correctness. Recording provenance is what keeps those two things from being
 * confused, and what turns "how much of this is actually verified?" into a
 * number instead of a shrug.
 */
import { readdirSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export const VECTORS_DIR = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../core/conformance/vectors"
);

/**
 * Where a vector's expected bytes came from, in ascending order of evidential
 * weight. Only `published` and `issued` are evidence about the outside world.
 */
export const VECTOR_TIERS = ["synthetic", "published", "issued"] as const;
export type VectorTier = (typeof VECTOR_TIERS)[number];

export const TIER_DESCRIPTIONS: Record<VectorTier, string> = {
  synthetic:
    "Produced by this implementation. Guards against regressions; proves nothing about spec conformance.",
  published:
    "Taken from AAMVA-published or jurisdiction-published test material. The strongest available evidence.",
  issued: "Decoded from a real issued credential and anonymised. Evidence of real-world parity."
};

/** Tiers that count as evidence the implementation matches external reality. */
export const REAL_WORLD_TIERS: readonly VectorTier[] = ["published", "issued"];

export interface VectorProvenance {
  tier: VectorTier;
  /** Where the bytes came from. For synthetic vectors, the generating script. */
  source: string;
  /** ISO date (YYYY-MM-DD) the source was captured. Null for synthetic. */
  capturedAt: string | null;
  /** Who checked the bytes against the source, or null if nobody has. */
  verifiedBy: string | null;
  /** How PII was replaced, for `issued` vectors. */
  anonymization?: string;
  notes?: string;
}

export interface ConformanceVector {
  id: string;
  state: string;
  version: string;
  subfileType: "DL" | "ID";
  description: string;
  provenance: VectorProvenance;
  input: Record<string, string>;
  expectedBytes: string;
}

export function loadVectors(): ConformanceVector[] {
  return readdirSync(VECTORS_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(readFileSync(resolve(VECTORS_DIR, f), "utf8")) as ConformanceVector);
}

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

/** Structural problems with a vector's provenance block, as readable strings. */
export function validateProvenance(vector: ConformanceVector): string[] {
  const problems: string[] = [];
  const p = vector.provenance;

  if (!p) return [`${vector.id}: missing provenance block`];

  if (!VECTOR_TIERS.includes(p.tier)) {
    problems.push(`${vector.id}: unknown tier "${p.tier}"`);
  }
  if (!p.source || !p.source.trim()) {
    problems.push(`${vector.id}: provenance.source must say where the bytes came from`);
  }
  if (p.capturedAt !== null && !ISO_DATE.test(p.capturedAt ?? "")) {
    problems.push(`${vector.id}: provenance.capturedAt must be YYYY-MM-DD or null`);
  }

  if (REAL_WORLD_TIERS.includes(p.tier)) {
    // A real-world vector with no capture date cannot be assessed for staleness,
    // and one nobody verified is just an assertion.
    if (!p.capturedAt) {
      problems.push(`${vector.id}: a ${p.tier} vector must record capturedAt`);
    }
    if (!p.verifiedBy) {
      problems.push(`${vector.id}: a ${p.tier} vector must record verifiedBy`);
    }
    if (p.tier === "issued" && !p.anonymization) {
      problems.push(`${vector.id}: an issued vector must document how PII was replaced`);
    }
  } else if (p.capturedAt !== null) {
    problems.push(`${vector.id}: a synthetic vector should have capturedAt null`);
  }

  return problems;
}

export interface CoverageReport {
  total: number;
  byTier: Record<VectorTier, number>;
  /** Jurisdictions with at least one published/issued vector. */
  realWorldJurisdictions: string[];
  /** Jurisdictions with only synthetic vectors, or none at all. */
  unverifiedJurisdictions: string[];
  realWorldVectorCount: number;
}

export function computeCoverage(
  vectors: ConformanceVector[],
  allJurisdictions: readonly string[]
): CoverageReport {
  const byTier = { synthetic: 0, published: 0, issued: 0 } as Record<VectorTier, number>;
  const realWorld = new Set<string>();

  for (const v of vectors) {
    const tier = v.provenance?.tier;
    if (tier && tier in byTier) byTier[tier] += 1;
    if (tier && REAL_WORLD_TIERS.includes(tier)) realWorld.add(v.state);
  }

  return {
    total: vectors.length,
    byTier,
    realWorldJurisdictions: [...realWorld].sort(),
    unverifiedJurisdictions: allJurisdictions.filter((j) => !realWorld.has(j)).sort(),
    realWorldVectorCount: byTier.published + byTier.issued
  };
}

export function formatCoverage(report: CoverageReport, totalJurisdictions: number): string {
  const verified = report.realWorldJurisdictions.length;
  const pct = ((verified / totalJurisdictions) * 100).toFixed(1);
  return [
    `Conformance corpus: ${report.total} vector(s)`,
    `  synthetic (regression only): ${report.byTier.synthetic}`,
    `  published (AAMVA test material): ${report.byTier.published}`,
    `  issued (anonymised real credential): ${report.byTier.issued}`,
    `Jurisdictions with real-world evidence: ${verified}/${totalJurisdictions} (${pct}%)`
  ].join("\n");
}
