import React, { useEffect, useRef, useState } from "react";
import bwipjs from "bwip-js";
import {
  ChevronDown,
  ChevronRight,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  FileImage,
  FileCode2,
  Copy,
  ArrowDownToLine
} from "lucide-react";
import { useFormStore } from "../hooks/useFormStore";
import { generateAAMVAPayload } from "../core/generator";
import { getFieldsForStateAndVersion } from "../core/schema";
import { decodeAAMVA } from "../core/decoder";
import { getValidationIssues } from "../core/validation";
import { useToast } from "./Toast";

const BWIP_OPTIONS = {
  bcid: "pdf417",
  scale: 2,
  columns: 5,
  eclevel: 5,
  compact: false as const,
  paddingwidth: 2,
  paddingheight: 2
} as const;

function CollapsibleSection({
  title,
  badge,
  badgeColor = "gray",
  children,
  defaultOpen = false
}: {
  title: string;
  badge?: string | number;
  badgeColor?: "gray" | "green" | "red" | "blue" | "amber";
  children: React.ReactNode;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);
  const badgeClasses = {
    gray: "bg-gray-200 dark:bg-[#333] text-gray-700 dark:text-gray-200",
    green: "bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300",
    red: "bg-red-100 dark:bg-red-900/40 text-red-700 dark:text-red-300",
    blue: "bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300",
    amber: "bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300"
  }[badgeColor];

  return (
    <div className="border border-gray-200 dark:border-dark-border rounded-md overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-3 py-2 bg-gray-50 dark:bg-dark-surface2 hover:bg-gray-100 dark:hover:bg-[#383838] transition-colors text-sm font-semibold text-gray-700 dark:text-gray-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-brand-500"
        aria-expanded={open}
      >
        <span className="flex items-center gap-2">
          {open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
          {title}
        </span>
        {badge !== undefined && (
          <span className={`text-xs px-1.5 py-0.5 rounded font-medium ${badgeClasses}`}>
            {badge}
          </span>
        )}
      </button>
      {open && <div className="px-3 py-2 bg-white dark:bg-dark-surface">{children}</div>}
    </div>
  );
}

interface BarcodePreviewProps {
  mobileHidden?: boolean;
  onScrollToField?: (code: string) => void;
}

export const BarcodePreview: React.FC<BarcodePreviewProps> = ({
  mobileHidden = false,
  onScrollToField
}) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const { state, version, fields, strictMode, subfileType } = useFormStore();
  const [error, setError] = useState<string | null>(null);
  const [payloadStr, setPayloadStr] = useState<string>("");
  const toast = useToast();

  useEffect(() => {
    const generate = () => {
      try {
        setError(null);
        const schemaFields = getFieldsForStateAndVersion(state, version);
        const dataObj = { ...fields, DAJ: state };

        const payload = generateAAMVAPayload(state, version, schemaFields, dataObj, {
          strictMode,
          subfileType,
          autoGenerateDiscriminator: true
        });

        setPayloadStr(payload);

        if (canvasRef.current) {
          bwipjs.toCanvas(canvasRef.current, { ...BWIP_OPTIONS, text: payload });
        }
      } catch (err) {
        setError((err as Error).message);
        setPayloadStr("");
        if (canvasRef.current) {
          const ctx = canvasRef.current.getContext("2d");
          ctx?.clearRect(0, 0, canvasRef.current.width, canvasRef.current.height);
        }
      }
    };

    const id = setTimeout(generate, 300);
    return () => clearTimeout(id);
  }, [state, version, fields, strictMode, subfileType]);

  const handleExportPNG = () => {
    if (!canvasRef.current || error) return;
    const url = canvasRef.current.toDataURL("image/png");
    const a = document.createElement("a");
    a.href = url;
    a.download = `barcode_${state}_${version}.png`;
    a.click();
  };

  const handleExportSVG = () => {
    if (!payloadStr || error) return;
    try {
      // bwip-js toSVG returns an SVG string
      const svgStr = (
        bwipjs as unknown as { toSVG: (opts: Record<string, unknown>) => string }
      ).toSVG({
        ...BWIP_OPTIONS,
        text: payloadStr
      });
      const blob = new Blob([svgStr], { type: "image/svg+xml" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `barcode_${state}_${version}.svg`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      // Fallback: wrap the canvas PNG in an SVG element
      if (!canvasRef.current) return;
      const w = canvasRef.current.width;
      const h = canvasRef.current.height;
      const pngData = canvasRef.current.toDataURL("image/png");
      const fallbackSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><image href="${pngData}" width="${w}" height="${h}"/></svg>`;
      const blob = new Blob([fallbackSvg], { type: "image/svg+xml" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `barcode_${state}_${version}.svg`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  // Decoded output
  const decoded = payloadStr ? decodeAAMVA(payloadStr) : null;
  const decodedEntries = decoded?.json
    ? Object.entries(decoded.json).filter(([k]) => k !== "version" && k !== "state")
    : [];

  // Validation report
  const schemaFields = getFieldsForStateAndVersion(state, version);
  const issues = getValidationIssues(schemaFields, { ...fields, DAJ: state }, state, strictMode);
  const errorCount = issues.filter((i) => i.severity === "error").length;
  const warningCount = issues.filter((i) => i.severity === "warning").length;
  const issueCount = issues.length;
  const reportBadge =
    issueCount === 0
      ? "Pass"
      : warningCount === 0
        ? `${errorCount} error${errorCount === 1 ? "" : "s"}`
        : errorCount === 0
          ? `${warningCount} warning${warningCount === 1 ? "" : "s"}`
          : `${errorCount} error${errorCount === 1 ? "" : "s"} · ${warningCount} warning${warningCount === 1 ? "" : "s"}`;
  const reportBadgeColor: "green" | "red" | "amber" =
    issueCount === 0 ? "green" : errorCount > 0 ? "red" : "amber";

  return (
    <aside
      className={`dmv-preview w-full lg:w-80 bg-gray-50 dark:bg-dark-surface border-t lg:border-t-0 lg:border-l border-gray-200 dark:border-dark-border z-10 p-4 flex flex-col gap-4 shadow-sm overflow-y-auto ${
        mobileHidden ? "hidden lg:flex" : "flex"
      }`}
      aria-label="Barcode preview and diagnostics"
    >
      <h2 className="text-lg font-medium tracking-tight text-gray-900 dark:text-gray-100">
        Preview
      </h2>

      {/* Canvas */}
      <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-dark-border p-4 rounded-md flex items-center justify-center min-h-[150px] relative overflow-hidden">
        <canvas ref={canvasRef} className="max-w-full" aria-label="PDF417 barcode preview" />
        {error && (
          <div
            role="alert"
            className="absolute inset-0 bg-red-50 dark:bg-red-900/60 bg-opacity-90 flex items-center justify-center p-3 text-center text-red-600 dark:text-red-300 text-sm font-semibold border border-red-200 dark:border-red-700 rounded-md"
          >
            {error}
          </div>
        )}
      </div>

      {/* Export buttons */}
      <div className="flex gap-2">
        <button
          onClick={handleExportPNG}
          disabled={!!error || !payloadStr}
          aria-label="Export barcode as PNG"
          className="flex-1 flex items-center justify-center gap-1.5 bg-brand-600 hover:bg-brand-700 disabled:opacity-40 disabled:cursor-not-allowed text-white py-1.5 rounded shadow text-sm font-medium transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 focus-visible:ring-offset-1 focus-visible:ring-offset-white dark:focus-visible:ring-offset-dark-surface"
        >
          <FileImage size={14} />
          PNG
        </button>
        <button
          onClick={handleExportSVG}
          disabled={!!error || !payloadStr}
          aria-label="Export barcode as SVG"
          className="flex-1 flex items-center justify-center gap-1.5 bg-gray-800 hover:bg-gray-900 dark:bg-dark-surface2 dark:hover:bg-[#383838] disabled:opacity-40 disabled:cursor-not-allowed text-white py-1.5 rounded shadow text-sm font-medium transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 focus-visible:ring-offset-1 focus-visible:ring-offset-white dark:focus-visible:ring-offset-dark-surface"
        >
          <FileCode2 size={14} />
          SVG
        </button>
      </div>

      {/* Raw Payload Inspector */}
      <CollapsibleSection
        title="Raw Payload"
        badge={payloadStr.length || undefined}
        badgeColor="blue"
        defaultOpen
      >
        <div className="relative">
          <textarea
            readOnly
            value={payloadStr}
            aria-label="Raw AAMVA payload string"
            className="w-full h-32 p-2 pr-9 border border-gray-200 dark:border-gray-600 rounded bg-gray-50 dark:bg-gray-900 text-xs font-mono text-gray-700 dark:text-gray-300 resize-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
          />
          <button
            type="button"
            onClick={async () => {
              if (!payloadStr) return;
              try {
                await navigator.clipboard.writeText(payloadStr);
                toast.success("Payload copied to clipboard");
              } catch {
                toast.error("Could not copy payload");
              }
            }}
            disabled={!payloadStr}
            aria-label="Copy raw payload to clipboard"
            title="Copy payload"
            className="absolute top-1.5 right-1.5 p-1.5 rounded bg-white dark:bg-dark-surface2 border border-gray-200 dark:border-gray-600 text-gray-600 dark:text-gray-300 hover:text-brand-600 dark:hover:text-brand-400 hover:border-brand-300 dark:hover:border-brand-700 transition shadow-sm disabled:opacity-40 disabled:cursor-not-allowed focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
          >
            <Copy size={13} />
          </button>
        </div>
      </CollapsibleSection>

      {/* Validation Report */}
      <CollapsibleSection
        title="Validation Report"
        badge={reportBadge}
        badgeColor={reportBadgeColor}
        defaultOpen={issueCount > 0}
      >
        {issueCount === 0 ? (
          <div className="flex items-center gap-2 py-1 text-sm text-green-700 dark:text-green-400">
            <CheckCircle2 size={15} />
            All fields pass validation
          </div>
        ) : (
          <>
            {errorCount > 0 && (
              <div className="mb-2 flex justify-end">
                <button
                  type="button"
                  onClick={() => {
                    const firstError = issues.find((i) => i.severity === "error");
                    if (!firstError) return;
                    if (onScrollToField) {
                      onScrollToField(firstError.code);
                    } else {
                      const el = document.getElementById(firstError.code);
                      el?.scrollIntoView({ behavior: "smooth", block: "center" });
                      el?.focus?.();
                    }
                  }}
                  className="flex items-center gap-1 text-xs px-2 py-1 rounded bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-300 hover:bg-red-100 dark:hover:bg-red-900/50 transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500"
                  aria-label="Scroll to first error"
                >
                  <ArrowDownToLine size={12} />
                  Scroll to first error
                </button>
              </div>
            )}
            <ul className="space-y-1.5 pt-1" role="list" aria-label="Validation issues">
              {issues.map((issue, idx) => {
                const isWarn = issue.severity === "warning";
                const Icon = isWarn ? AlertTriangle : XCircle;
                const iconClass = isWarn
                  ? "text-amber-500 mt-0.5 shrink-0"
                  : "text-red-500 mt-0.5 shrink-0";
                const messageClass = isWarn
                  ? "text-amber-700 dark:text-amber-300"
                  : "text-red-600 dark:text-red-400";
                return (
                  <li
                    key={`${issue.code}:${issue.severity}:${idx}`}
                    className="flex items-start gap-2 text-xs"
                    data-severity={issue.severity}
                  >
                    <Icon size={13} className={iconClass} aria-hidden />
                    <span>
                      <span className="font-mono font-semibold text-gray-700 dark:text-gray-200">
                        {issue.code}
                      </span>{" "}
                      <span className="text-gray-500 dark:text-gray-400">({issue.label}):</span>{" "}
                      <span className={messageClass}>{issue.message}</span>
                    </span>
                  </li>
                );
              })}
            </ul>
          </>
        )}
      </CollapsibleSection>

      {/* Decoded Output */}
      <CollapsibleSection
        title="Decoded Output"
        badge={decodedEntries.length || undefined}
        badgeColor="blue"
      >
        {decoded?.error ? (
          <p className="text-xs text-red-600 dark:text-red-400 py-1">{decoded.error}</p>
        ) : decodedEntries.length === 0 ? (
          <p className="text-xs text-gray-400 py-1">No payload to decode yet.</p>
        ) : (
          <table className="w-full text-xs border-collapse" aria-label="Decoded AAMVA fields">
            <thead>
              <tr className="text-left text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-600">
                <th className="py-1 pr-2 font-semibold w-12">Code</th>
                <th className="py-1 font-semibold">Value</th>
              </tr>
            </thead>
            <tbody>
              {decodedEntries.map(([code, val]) => (
                <tr
                  key={code}
                  className="border-b border-gray-100 dark:border-gray-700 last:border-0"
                >
                  <td className="py-1 pr-2 font-mono font-semibold text-blue-700 dark:text-blue-400">
                    {code}
                  </td>
                  <td className="py-1 font-mono text-gray-700 dark:text-gray-300 break-all">
                    {val}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </CollapsibleSection>
    </aside>
  );
};
