import React, { useEffect, useRef, useState } from 'react';
import bwipjs from 'bwip-js';
import { useFormStore } from '../hooks/useFormStore';
import { generateAAMVAPayload } from '../core/generator';
import { getFieldsForStateAndVersion } from '../core/schema';

export const BarcodePreview: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const { state, version, fields, strictMode, subfileType } = useFormStore();
  const [error, setError] = useState<string | null>(null);
  const [payloadStr, setPayloadStr] = useState<string>('');

  useEffect(() => {
    const generateBarcode = () => {
      try {
        setError(null);
        const schemaFields = getFieldsForStateAndVersion(state, version);

        // Build data object ensuring DAJ is set
        const dataObj = { ...fields, DAJ: state };

        const payload = generateAAMVAPayload(state, version, schemaFields, dataObj, {
          strictMode,
          subfileType,
          autoGenerateDiscriminator: true,
        });

        setPayloadStr(payload);

        if (canvasRef.current) {
          bwipjs.toCanvas(canvasRef.current, {
            bcid: 'pdf417',
            text: payload,
            scale: 2,
            columns: 5,
            eclevel: 5,
            compact: false,
            paddingwidth: 2,
            paddingheight: 2,
          });
        }
      } catch (err) {
        setError((err as Error).message);
        if (canvasRef.current) {
          const ctx = canvasRef.current.getContext('2d');
          if (ctx) {
            ctx.clearRect(0, 0, canvasRef.current.width, canvasRef.current.height);
          }
        }
      }
    };

    // Debounce barcode generation to prevent lag while typing
    const timeoutId = setTimeout(generateBarcode, 300);
    return () => clearTimeout(timeoutId);
  }, [state, version, fields, strictMode, subfileType]);

  const handleExportPNG = () => {
    if (!canvasRef.current || error) return;
    const url = canvasRef.current.toDataURL('image/png');
    const a = document.createElement('a');
    a.href = url;
    a.download = `barcode_${state}_${version}.png`;
    a.click();
  };

  return (
    <div className="w-80 bg-gray-50 border-l border-gray-200 p-4 flex flex-col shadow-sm">
      <h2 className="text-lg font-semibold mb-4">Preview</h2>

      <div className="bg-white border p-4 rounded-md flex items-center justify-center min-h-[150px] relative overflow-hidden">
        <canvas ref={canvasRef} className="max-w-full" />
        {error && (
          <div className="absolute inset-0 bg-red-50 bg-opacity-90 flex items-center justify-center p-2 text-center text-red-600 text-sm font-semibold border border-red-200 rounded-md">
            {error}
          </div>
        )}
      </div>

      <div className="mt-4 flex flex-col space-y-2">
        <button
          onClick={handleExportPNG}
          disabled={!!error}
          className="bg-blue-600 text-white py-2 rounded shadow hover:bg-blue-700 disabled:opacity-50"
        >
          Export PNG
        </button>
      </div>

      <div className="mt-8 flex-1">
        <h3 className="text-sm font-semibold text-gray-700 mb-2">Raw Payload Inspector</h3>
        <textarea
          readOnly
          value={payloadStr}
          className="w-full h-48 p-2 border border-gray-300 rounded bg-gray-100 text-xs font-mono"
        />
      </div>
    </div>
  );
};