import React, { useRef, useState } from "react";
import { Upload, Download, FileText, AlertCircle, CheckCircle } from "lucide-react";
import { generateAAMVAPayload } from "../core/generator";
import { getFieldsForStateAndVersion } from "../core/schema";
import { jsPDF } from "jspdf";
import bwipjs from "bwip-js";

interface BatchEntry {
  state: string;
  version: string;
  subfileType?: "DL" | "ID";
  [key: string]: string | undefined;
}

/** Convert canvas pixels to PDF points (jsPDF default unit is pt, 72pt = 1in).
 *  We assume screen pixels at 96 DPI: 1px = 72/96 pt = 0.75 pt.
 *  Then we constrain to fit within the page content width. */
function canvasToPdfDimensions(
  canvasWidth: number,
  canvasHeight: number,
  maxWidthPt: number
): { widthPt: number; heightPt: number } {
  const ptPerPx = 72 / 96;
  const naturalWidthPt = canvasWidth * ptPerPx;
  const naturalHeightPt = canvasHeight * ptPerPx;

  if (naturalWidthPt <= maxWidthPt) {
    return { widthPt: naturalWidthPt, heightPt: naturalHeightPt };
  }

  const scale = maxWidthPt / naturalWidthPt;
  return { widthPt: maxWidthPt, heightPt: naturalHeightPt * scale };
}

export const BatchProcessor: React.FC = () => {
  const [file, setFile] = useState<File | null>(null);
  const [processing, setProcessing] = useState(false);
  const [results, setResults] = useState<{
    success: number;
    failed: number;
    errors: string[];
  } | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
      setResults(null);
    }
  };

  const processBatch = async () => {
    if (!file) return;
    setProcessing(true);
    setResults(null);

    try {
      const text = await file.text();
      const raw: unknown = JSON.parse(text);

      if (!Array.isArray(raw)) {
        throw new Error("JSON file must contain an array of objects.");
      }

      const data = raw as BatchEntry[];
      let successCount = 0;
      let failedCount = 0;
      const errors: string[] = [];

      // jsPDF default page: 595.28 × 841.89 pt (A4). Use 40pt margins.
      const PAGE_WIDTH_PT = 595.28;
      const MARGIN_PT = 40;
      const CONTENT_WIDTH_PT = PAGE_WIDTH_PT - MARGIN_PT * 2;

      const pdf = new jsPDF({ unit: "pt", format: "a4" });

      for (let i = 0; i < data.length; i++) {
        const row = data[i];
        try {
          if (!row.state || !row.version) {
            throw new Error(`Row ${i + 1}: Missing 'state' or 'version'`);
          }

          const schemaFields = getFieldsForStateAndVersion(row.state, row.version);
          const rowData = Object.fromEntries(
            Object.entries(row).map(([k, v]) => [k, v ?? ""])
          ) as Record<string, string>;

          const payload = generateAAMVAPayload(row.state, row.version, schemaFields, rowData, {
            strictMode: true,
            autoGenerateDiscriminator: true,
            subfileType: row.subfileType || "DL"
          });

          const canvas = document.createElement("canvas");
          bwipjs.toCanvas(canvas, {
            bcid: "pdf417",
            text: payload,
            scale: 3,
            columns: 5,
            eclevel: 5,
            paddingwidth: 2,
            paddingheight: 2
          });

          const imgData = canvas.toDataURL("image/png");
          const { widthPt, heightPt } = canvasToPdfDimensions(
            canvas.width,
            canvas.height,
            CONTENT_WIDTH_PT
          );

          if (successCount > 0) pdf.addPage();

          pdf.setFontSize(10);
          pdf.setTextColor(60, 60, 60);
          pdf.text(
            `Barcode ${i + 1} — ${row.state} v${row.version} (${row.subfileType ?? "DL"})`,
            MARGIN_PT,
            MARGIN_PT - 6
          );
          pdf.addImage(imgData, "PNG", MARGIN_PT, MARGIN_PT, widthPt, heightPt);

          successCount++;
        } catch (err) {
          failedCount++;
          errors.push(`Row ${i + 1}: ${(err as Error).message}`);
        }
      }

      if (successCount > 0) {
        pdf.save("batch_export.pdf");
      }

      setResults({ success: successCount, failed: failedCount, errors });
    } catch (err) {
      setResults({ success: 0, failed: 1, errors: [(err as Error).message] });
    } finally {
      setProcessing(false);
    }
  };

  return (
    <div className="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-6 flex flex-col">
      <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100 mb-4 flex items-center">
        <FileText className="mr-2 h-5 w-5 text-blue-600" />
        Batch Processing
      </h3>

      <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
        Upload a JSON file containing an array of payload objects. Each entry needs at least{" "}
        <code className="font-mono bg-gray-100 dark:bg-gray-700 px-1 rounded">state</code> and{" "}
        <code className="font-mono bg-gray-100 dark:bg-gray-700 px-1 rounded">version</code>. The
        system will process them and download a single multi-page PDF.
      </p>

      <div className="flex items-center space-x-4">
        <input
          type="file"
          accept=".json,application/json"
          ref={fileInputRef}
          onChange={handleFileChange}
          className="hidden"
          aria-label="Select batch JSON file"
        />
        <button
          onClick={() => fileInputRef.current?.click()}
          className="flex items-center space-x-2 bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-100 px-4 py-2 border border-gray-300 dark:border-gray-600 rounded text-sm transition font-medium"
          aria-label="Select JSON file for batch processing"
        >
          <Upload size={16} />
          <span>Select JSON File</span>
        </button>

        <span className="text-sm text-gray-500 dark:text-gray-400 font-medium truncate max-w-xs">
          {file ? file.name : "No file selected"}
        </span>
      </div>

      <div className="mt-4">
        <button
          onClick={processBatch}
          disabled={!file || processing}
          className="flex items-center space-x-2 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 dark:disabled:bg-blue-900 text-white px-6 py-2 rounded text-sm transition shadow font-medium"
          aria-busy={processing}
        >
          <Download size={16} />
          <span>{processing ? "Processing…" : "Generate & Download PDF"}</span>
        </button>
      </div>

      {results && (
        <div
          role="status"
          className={`mt-4 p-4 rounded text-sm border ${
            results.failed > 0
              ? "bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-700"
              : "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-700"
          }`}
        >
          <div className="flex items-center font-semibold mb-2 text-gray-800 dark:text-gray-100">
            {results.failed > 0 ? (
              <AlertCircle className="h-5 w-5 text-red-600 mr-2" />
            ) : (
              <CheckCircle className="h-5 w-5 text-green-600 mr-2" />
            )}
            {results.success} succeeded, {results.failed} failed
          </div>
          {results.errors.length > 0 && (
            <ul className="list-disc list-inside text-red-700 dark:text-red-400 text-xs mt-2 space-y-1">
              {results.errors.map((err, idx) => (
                <li key={idx}>{err}</li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
};
