import React, { useRef, useState } from 'react';
import { Upload, Download, FileText, AlertCircle, CheckCircle } from 'lucide-react';
import { generateAAMVAPayload } from '../core/generator';
import { getFieldsForStateAndVersion } from '../core/schema';
import { jsPDF } from 'jspdf';
import bwipjs from 'bwip-js';

export const BatchProcessor: React.FC = () => {
  const [file, setFile] = useState<File | null>(null);
  const [processing, setProcessing] = useState(false);
  const [results, setResults] = useState<{ success: number; failed: number; errors: string[] } | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
      setResults(null);
    }
  };

  const processBatch = async () => {
    if (!file) return;
    setProcessing(true);
    setResults(null);

    try {
      const text = await file.text();
      const data: any[] = JSON.parse(text);

      if (!Array.isArray(data)) {
        throw new Error('JSON file must contain an array of objects.');
      }

      let successCount = 0;
      let failedCount = 0;
      const errors: string[] = [];
      const pdf = new jsPDF({ unit: 'pt' });

      for (let i = 0; i < data.length; i++) {
        const row = data[i];
        try {
          if (!row.state || !row.version) {
            throw new Error(`Row ${i + 1}: Missing 'state' or 'version'`);
          }

          const schemaFields = getFieldsForStateAndVersion(row.state, row.version);
          const payload = generateAAMVAPayload(row.state, row.version, schemaFields, row, {
            strictMode: true,
            autoGenerateDiscriminator: true,
            subfileType: row.subfileType || 'DL',
          });

          const canvas = document.createElement('canvas');
          bwipjs.toCanvas(canvas, {
            bcid: 'pdf417',
            text: payload,
            scale: 3,
            columns: 5,
            eclevel: 5,
            paddingwidth: 2,
            paddingheight: 2,
          });

          const imgData = canvas.toDataURL('image/png');

          if (successCount > 0) pdf.addPage();

          pdf.setFontSize(10);
          pdf.text(`Barcode ${i + 1} - ${row.state} (v${row.version})`, 40, 40);
          pdf.addImage(imgData, 'PNG', 40, 60, canvas.width, canvas.height);

          successCount++;
        } catch (err) {
          failedCount++;
          errors.push(`Row ${i + 1}: ${(err as Error).message}`);
        }
      }

      if (successCount > 0) {
        pdf.save('batch_export.pdf');
      }

      setResults({ success: successCount, failed: failedCount, errors });
    } catch (err) {
      setResults({ success: 0, failed: 1, errors: [(err as Error).message] });
    } finally {
      setProcessing(false);
    }
  };

  return (
    <div className="bg-white border-t border-gray-200 p-6 flex flex-col">
      <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center">
        <FileText className="mr-2 h-5 w-5 text-blue-600" />
        Batch Processing
      </h3>

      <p className="text-sm text-gray-600 mb-4">
        Upload a JSON file containing an array of payload objects. The system will process them and download a single multi-page PDF with the generated barcodes.
      </p>

      <div className="flex items-center space-x-4">
        <input
          type="file"
          accept=".json"
          ref={fileInputRef}
          onChange={handleFileChange}
          className="hidden"
        />
        <button
          onClick={() => fileInputRef.current?.click()}
          className="flex items-center space-x-2 bg-gray-100 hover:bg-gray-200 text-gray-800 px-4 py-2 border border-gray-300 rounded text-sm transition font-medium"
        >
          <Upload size={16} />
          <span>Select JSON File</span>
        </button>

        <span className="text-sm text-gray-500 font-medium">
          {file ? file.name : 'No file selected'}
        </span>
      </div>

      <div className="mt-4">
        <button
          onClick={processBatch}
          disabled={!file || processing}
          className="flex items-center space-x-2 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 text-white px-6 py-2 rounded text-sm transition shadow font-medium"
        >
          <Download size={16} />
          <span>{processing ? 'Processing...' : 'Generate & Download PDF'}</span>
        </button>
      </div>

      {results && (
        <div className={`mt-4 p-4 rounded text-sm border ${results.failed > 0 ? 'bg-red-50 border-red-200' : 'bg-green-50 border-green-200'}`}>
          <div className="flex items-center font-semibold mb-2">
            {results.failed > 0 ? (
              <AlertCircle className="h-5 w-5 text-red-600 mr-2" />
            ) : (
              <CheckCircle className="h-5 w-5 text-green-600 mr-2" />
            )}
            Results: {results.success} Successful, {results.failed} Failed
          </div>
          {results.errors.length > 0 && (
            <ul className="list-disc list-inside text-red-700 text-xs mt-2 space-y-1">
              {results.errors.map((err, idx) => (
                <li key={idx}>{err}</li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
};