import { AAMVA_STATES, isJurisdictionSupported } from "./states";
import { AAMVA_VERSIONS, getMandatoryFields, AAMVAField } from "./schema";
import { AAMVA_STATE_RULES, evaluateFieldValue, validateCrossFieldConsistency } from "./validation";
import { validateAAMVAPayloadStructure } from "./decoder";
import { secureGetRandomInt } from "./crypto";

export interface GenerateOptions {
  strictMode?: boolean;
  autoGenerateDiscriminator?: boolean;
  subfileType?: "DL" | "ID";
}

/**
 * Field codes `autoGenerateDiscriminator` is allowed to invent.
 *
 * DCF is the document discriminator — a per-print serial the issuing system
 * assigns, which is what this option is named for — and DDB is the card
 * revision date, a property of the card stock rather than of the holder.
 *
 * DAQ is deliberately absent. It is the cardholder's actual customer/licence
 * number and it is mandatory in every version, so auto-filling it both put an
 * invented identifier into the barcode and silently defeated the missing
 * mandatory-field check for the one field nobody can guess.
 */
const AUTO_GENERATED_CODES = new Set(["DCF", "DDB"]);

export function generateDocumentDiscriminator(length = 12): string {
  const charset = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const chars = [];

  if (typeof crypto !== "undefined" && typeof crypto.getRandomValues === "function") {
    const bytes = new Uint8Array(length);
    crypto.getRandomValues(bytes);
    for (let i = 0; i < length; i++) {
      chars.push(charset[(bytes[i] ?? 0) % charset.length]);
    }
  } else {
    for (let i = 0; i < length; i++) {
      chars.push(charset[secureGetRandomInt(charset.length)]);
    }
  }
  return chars.join("");
}

export function generateStateDiscriminator(stateCode?: string): string {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DCF) {
    return AAMVA_STATE_RULES[stateCode].generators!.DCF();
  }
  return generateDocumentDiscriminator();
}

export function generateStateLicenseNumber(stateCode?: string): string {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DAQ) {
    return AAMVA_STATE_RULES[stateCode].generators!.DAQ();
  }
  let s = "";
  for (let i = 0; i < 9; i++) s += secureGetRandomInt(10);
  return s;
}

export function generateStateCardRevisionDate(
  stateCode?: string,
  issueDateStr?: string
): string | null {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DDB) {
    return AAMVA_STATE_RULES[stateCode].generators!.DDB(issueDateStr);
  }
  return null;
}

export function generateAAMVAPayload(
  stateCode: string,
  version: string,
  fields: AAMVAField[],
  inputData: Record<string, string>,
  options: GenerateOptions = {}
): string {
  const strictMode = options.strictMode === true;
  const subfileType = options.subfileType || "DL";

  // Work on a copy. This used to normalise and auto-fill the caller's object in
  // place, so generating a preview quietly rewrote the values the caller still
  // held — an undeclared side effect for a function that returns a string.
  const dataObj: Record<string, string> = { ...inputData };

  if (!AAMVA_STATES[stateCode]) throw new Error(`Unknown state code: ${stateCode}`);

  if (!isJurisdictionSupported(stateCode)) {
    throw new Error(`Unsupported jurisdiction for generation: ${stateCode}`);
  }

  if (!AAMVA_VERSIONS[version]) throw new Error(`Unsupported AAMVA version: ${version}`);

  if (strictMode) {
    const jurisdictionVersion = AAMVA_STATES[stateCode].aamvaVersion;
    if (version !== jurisdictionVersion) {
      throw new Error(
        `Strict Mode: version ${version} does not match ${stateCode} compliance profile (${jurisdictionVersion})`
      );
    }
  }

  if (options.autoGenerateDiscriminator && AAMVA_STATE_RULES[stateCode]?.generators) {
    const generators = AAMVA_STATE_RULES[stateCode].generators!;
    const presentCodes = new Set(fields.map((f) => f.code));
    for (const [code, generator] of Object.entries(generators)) {
      if (!AUTO_GENERATED_CODES.has(code)) continue;
      if (!presentCodes.has(code) || dataObj[code]) continue;
      dataObj[code] = code === "DDB" ? generator(dataObj.DBD) : generator();
    }
  }

  if (options.autoGenerateDiscriminator && !dataObj.DCF && fields.some((f) => f.code === "DCF")) {
    dataObj.DCF = generateDocumentDiscriminator();
  }

  // Normalise before the mandatory/format checks so values that arrive from an
  // import or a scan are judged on their real content. Decoded AAMVA values
  // carry the encoder's fixed-width space padding, and a required field holding
  // nothing but whitespace is missing, not present.
  for (const field of fields) {
    const raw = dataObj[field.code];
    if (raw) {
      let val = raw;
      if (["string", "char", "zip"].includes(field.type)) val = val.toUpperCase();
      dataObj[field.code] = val
        .normalize("NFKD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[^\x20-\x7e]/g, "")
        // eslint-disable-next-line no-control-regex
        .replace(/[\x00-\x1f\x7f]/g, "")
        .trim();
    }
  }

  const mandatoryFields = getMandatoryFields(stateCode, version);
  const missing = mandatoryFields
    .filter((f) => !dataObj[f.code])
    .map((f) => `${f.label} (${f.code})`);

  if (missing.length > 0) {
    throw new Error(
      `Missing mandatory fields for ${stateCode} (v${version}): ${missing.join(", ")}`
    );
  }

  if (dataObj.DAJ && dataObj.DAJ !== stateCode) {
    if (strictMode)
      throw new Error(`Strict Mode: DAJ (${dataObj.DAJ}) must match state code (${stateCode})`);
    dataObj.DAJ = stateCode;
  }

  // `evaluateFieldValue` rather than `validateFieldValue`, so the jurisdiction
  // rule packs are consulted here too. They were previously only reachable from
  // the UI, which meant strict mode surfaced a pack warning in the validation
  // panel and then generated the payload anyway — despite strict mode being
  // documented as "warnings are treated as errors and block generation".
  const invalidFields: string[] = [];
  const advisories: string[] = [];
  for (const field of fields) {
    const val = dataObj[field.code];
    if (!val) continue;
    // Evaluated without strict promotion so an advisory stays distinguishable
    // from a hard failure and can be reported with its own explanation below.
    const result = evaluateFieldValue(field, val, stateCode);
    if (!result.ok) {
      invalidFields.push(`${field.label} (${field.code})`);
    } else if (result.severity === "warning") {
      advisories.push(`${field.label} (${field.code}): ${result.message}`);
    }
  }

  if (invalidFields.length > 0) {
    throw new Error(
      `Invalid field values for ${stateCode} (v${version}): ${invalidFields.join(", ")}`
    );
  }

  const crossFieldIssues = validateCrossFieldConsistency(dataObj, fields, stateCode);
  const blockingCrossFieldIssues = crossFieldIssues.filter(
    (issue) => issue.severity === "error" || (strictMode && issue.severity === "warning")
  );

  if (blockingCrossFieldIssues.length > 0) {
    const details = blockingCrossFieldIssues
      .map((issue) => `[${issue.severity.toUpperCase()}] ${issue.message}`)
      .join(" ");
    throw new Error(`Cross-field validation failed for ${stateCode} (v${version}): ${details}`);
  }

  // Reported last, so a hard field error or a cross-field contradiction — both
  // more actionable — is what the user sees first when several things are wrong.
  if (strictMode && advisories.length > 0) {
    throw new Error(
      `Strict Mode: jurisdiction advisories for ${stateCode} (v${version}): ${advisories.join(" ")}`
    );
  }

  const stateDef = AAMVA_STATES[stateCode];
  const iin = stateDef.IIN;
  const jurisVersion = "00";

  const compliance = "@";
  const dataElementSeparator = "\n";
  const recordSeparator = "\x1e";
  const segmentTerminator = "\r";
  const fileType = "ANSI ";

  const header =
    compliance +
    dataElementSeparator +
    recordSeparator +
    segmentTerminator +
    fileType +
    iin +
    version +
    jurisVersion;

  let subfileData = subfileType;

  for (const field of fields) {
    let val = dataObj[field.code];
    if (val !== undefined && val !== "") {
      if (field.code === "DAK") {
        const stripped = val.replace(/-/g, "");
        val = stripped.padEnd(11, " ").substring(0, 11);
      }
      subfileData += field.code + val + dataElementSeparator;
    }
  }

  subfileData += segmentTerminator;

  const numEntries = "01";
  const headerLength = 21 + 10;
  const offset = headerLength;

  const textEncoder = typeof TextEncoder !== "undefined" ? new TextEncoder() : null;
  const length = textEncoder ? textEncoder.encode(subfileData).length : subfileData.length;

  if (length > 9999)
    throw new Error("Generated subfile exceeds 4-digit directory length limit (9999 bytes).");

  const offsetStr = offset.toString().padStart(4, "0");
  const lengthStr = length.toString().padStart(4, "0");
  const subfileDir = subfileType + offsetStr + lengthStr;

  const payload = header + numEntries + subfileDir + subfileData;

  if (strictMode) {
    const strictStructure = validateAAMVAPayloadStructure(payload, true);
    if (!strictStructure.ok) {
      throw new Error(
        `Strict Mode: generated payload structure is invalid (${strictStructure.error})`
      );
    }
  }

  return payload;
}
