import { AAMVA_STATES, isJurisdictionSupported } from "./states";
import { AAMVA_VERSIONS, getMandatoryFields, AAMVAField } from "./schema";
import { AAMVA_STATE_RULES, validateCrossFieldConsistency, validateFieldValue } from "./validation";
import { validateAAMVAPayloadStructure } from "./decoder";

export interface GenerateOptions {
  strictMode?: boolean;
  autoGenerateDiscriminator?: boolean;
  subfileType?: "DL" | "ID";
}

export function generateDocumentDiscriminator(length = 12): string {
  const charset = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const chars = [];

  if (typeof crypto !== "undefined" && typeof crypto.getRandomValues === "function") {
    const bytes = new Uint8Array(length);
    crypto.getRandomValues(bytes);
    for (let i = 0; i < length; i++) {
      chars.push(charset[(bytes[i] ?? 0) % charset.length]);
    }
  } else {
    for (let i = 0; i < length; i++) {
      chars.push(charset[Math.floor(Math.random() * charset.length)]);
    }
  }
  return chars.join("");
}

export function generateStateDiscriminator(stateCode?: string): string {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DCF) {
    return AAMVA_STATE_RULES[stateCode].generators!.DCF();
  }
  return generateDocumentDiscriminator();
}

export function generateStateLicenseNumber(stateCode?: string): string {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DAQ) {
    return AAMVA_STATE_RULES[stateCode].generators!.DAQ();
  }
  let s = "";
  for (let i = 0; i < 9; i++) s += Math.floor(Math.random() * 10);
  return s;
}

export function generateStateCardRevisionDate(
  stateCode?: string,
  issueDateStr?: string
): string | null {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DDB) {
    return AAMVA_STATE_RULES[stateCode].generators!.DDB(issueDateStr);
  }
  return null;
}

export function generateAAMVAPayload(
  stateCode: string,
  version: string,
  fields: AAMVAField[],
  dataObj: Record<string, string>,
  options: GenerateOptions = {}
): string {
  const strictMode = options.strictMode === true;
  const subfileType = options.subfileType || "DL";

  if (!AAMVA_STATES[stateCode]) throw new Error(`Unknown state code: ${stateCode}`);

  if (!isJurisdictionSupported(stateCode)) {
    throw new Error(`Unsupported jurisdiction for generation: ${stateCode}`);
  }

  if (!AAMVA_VERSIONS[version]) throw new Error(`Unsupported AAMVA version: ${version}`);

  if (strictMode) {
    const jurisdictionVersion = AAMVA_STATES[stateCode].aamvaVersion;
    if (version !== jurisdictionVersion) {
      throw new Error(
        `Strict Mode: version ${version} does not match ${stateCode} compliance profile (${jurisdictionVersion})`
      );
    }
  }

  if (AAMVA_STATE_RULES[stateCode]?.generators) {
    const generators = AAMVA_STATE_RULES[stateCode].generators!;
    for (const [code, generator] of Object.entries(generators)) {
      if (options.autoGenerateDiscriminator && !dataObj[code]) {
        dataObj[code] = code === "DDB" ? generator(dataObj.DBD) : generator();
      }
    }
  }

  if (options.autoGenerateDiscriminator && !dataObj.DCF && fields.some((f) => f.code === "DCF")) {
    dataObj.DCF = generateDocumentDiscriminator();
  }

  const mandatoryFields = getMandatoryFields(stateCode, version);
  const missing = mandatoryFields
    .filter((f) => !dataObj[f.code])
    .map((f) => `${f.label} (${f.code})`);

  if (missing.length > 0) {
    throw new Error(
      `Missing mandatory fields for ${stateCode} (v${version}): ${missing.join(", ")}`
    );
  }

  if (dataObj.DAJ && dataObj.DAJ !== stateCode) {
    if (strictMode)
      throw new Error(`Strict Mode: DAJ (${dataObj.DAJ}) must match state code (${stateCode})`);
    dataObj.DAJ = stateCode;
  }

  for (const field of fields) {
    const raw = dataObj[field.code];
    if (raw) {
      let val = raw;
      if (["string", "char", "zip"].includes(field.type)) val = val.toUpperCase();
      dataObj[field.code] = val
        .normalize("NFKD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[^\x20-\x7e]/g, "")
        // eslint-disable-next-line no-control-regex
        .replace(/[\x00-\x1f\x7f]/g, "");
    }
  }

  const invalidFields = fields
    .filter((field) => {
      const val = dataObj[field.code];
      return val && val !== "" && !validateFieldValue(field, val, stateCode, strictMode);
    })
    .map((f) => `${f.label} (${f.code})`);

  if (invalidFields.length > 0) {
    throw new Error(
      `Invalid field values for ${stateCode} (v${version}): ${invalidFields.join(", ")}`
    );
  }

  const crossFieldIssues = validateCrossFieldConsistency(dataObj, fields);
  const blockingCrossFieldIssues = crossFieldIssues.filter(
    (issue) => issue.severity === "error" || (strictMode && issue.severity === "warning")
  );

  if (blockingCrossFieldIssues.length > 0) {
    const details = blockingCrossFieldIssues
      .map((issue) => `[${issue.severity.toUpperCase()}] ${issue.message}`)
      .join(" ");
    throw new Error(`Cross-field validation failed for ${stateCode} (v${version}): ${details}`);
  }

  const stateDef = AAMVA_STATES[stateCode];
  const iin = stateDef.IIN;
  const jurisVersion = "00";

  const compliance = "@";
  const dataElementSeparator = "\n";
  const recordSeparator = "\x1e";
  const segmentTerminator = "\r";
  const fileType = "ANSI ";

  const header =
    compliance +
    dataElementSeparator +
    recordSeparator +
    segmentTerminator +
    fileType +
    iin +
    version +
    jurisVersion;

  let subfileData = subfileType;

  for (const field of fields) {
    let val = dataObj[field.code];
    if (val !== undefined && val !== "") {
      if (field.code === "DAK") {
        const stripped = val.replace(/-/g, "");
        val = stripped.padEnd(11, " ").substring(0, 11);
      }
      subfileData += field.code + val + dataElementSeparator;
    }
  }

  subfileData += segmentTerminator;

  const numEntries = "01";
  const headerLength = 21 + 10;
  const offset = headerLength;

  const textEncoder = typeof TextEncoder !== "undefined" ? new TextEncoder() : null;
  const length = textEncoder ? textEncoder.encode(subfileData).length : subfileData.length;

  if (length > 9999)
    throw new Error("Generated subfile exceeds 4-digit directory length limit (9999 bytes).");

  const offsetStr = offset.toString().padStart(4, "0");
  const lengthStr = length.toString().padStart(4, "0");
  const subfileDir = subfileType + offsetStr + lengthStr;

  const payload = header + numEntries + subfileDir + subfileData;

  const actualLength = textEncoder ? textEncoder.encode(subfileData).length : subfileData.length;
  if (actualLength !== length) throw new Error("AAMVA payload directory length mismatch.");

  if (strictMode) {
    const strictStructure = validateAAMVAPayloadStructure(payload, true);
    if (!strictStructure.ok) {
      throw new Error(
        `Strict Mode: generated payload structure is invalid (${strictStructure.error})`
      );
    }
  }

  return payload;
}
