import { AAMVA_STATES, isJurisdictionSupported } from "./states";
import { AAMVA_VERSIONS, getMandatoryFields, AAMVAField } from "./schema";
import { AAMVA_STATE_RULES, evaluateFieldValue, validateCrossFieldConsistency } from "./validation";
import { getJurisdictionEncoding, shouldPadPostalCode } from "./jurisdictionRules";
import { validateAAMVAPayloadStructure } from "./decoder";
import { secureGetRandomInt } from "./crypto";

export interface GenerateOptions {
  strictMode?: boolean;
  autoGenerateDiscriminator?: boolean;
  subfileType?: "DL" | "ID";
}

/**
 * Field codes `autoGenerateDiscriminator` is allowed to invent.
 *
 * DCF is the document discriminator — a per-print serial the issuing system
 * assigns, which is what this option is named for — and DDB is the card
 * revision date, a property of the card stock rather than of the holder.
 *
 * DAQ is deliberately absent. It is the cardholder's actual customer/licence
 * number and it is mandatory in every version, so auto-filling it both put an
 * invented identifier into the barcode and silently defeated the missing
 * mandatory-field check for the one field nobody can guess.
 */
const AUTO_GENERATED_CODES = new Set(["DCF", "DDB"]);

const _textEncoder = typeof TextEncoder !== "undefined" ? new TextEncoder() : null;

/** Wire length in bytes — directory offsets and lengths count bytes, not code units. */
function byteLength(s: string): number {
  return _textEncoder ? _textEncoder.encode(s).length : s.length;
}

function pad4(n: number): string {
  return n.toString().padStart(4, "0");
}

/**
 * Applies a jurisdiction's observed element order to the schema field list.
 *
 * AAMVA does not mandate an order within the subfile, so schema order is the
 * default and remains correct. Where a jurisdiction is known to emit a specific
 * one, matching it makes our output byte-comparable to a real card. Codes the
 * order does not mention keep their schema order and follow the listed ones,
 * so a field added to the schema later cannot silently vanish from the payload.
 */
function orderFields(fields: AAMVAField[], order?: string[]): AAMVAField[] {
  if (!order || order.length === 0) return fields;
  const rank = new Map(order.map((code, i) => [code, i]));
  // Array.prototype.sort is stable, so unranked fields hold their schema order.
  return [...fields].sort(
    (a, b) =>
      (rank.get(a.code) ?? Number.MAX_SAFE_INTEGER) - (rank.get(b.code) ?? Number.MAX_SAFE_INTEGER)
  );
}

export function generateDocumentDiscriminator(length = 12): string {
  const charset = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const chars = [];

  if (typeof crypto !== "undefined" && typeof crypto.getRandomValues === "function") {
    const bytes = new Uint8Array(length);
    crypto.getRandomValues(bytes);
    for (let i = 0; i < length; i++) {
      chars.push(charset[(bytes[i] ?? 0) % charset.length]);
    }
  } else {
    for (let i = 0; i < length; i++) {
      chars.push(charset[secureGetRandomInt(charset.length)]);
    }
  }
  return chars.join("");
}

/**
 * A document discriminator in the jurisdiction's observed format.
 *
 * `issueDateStr` (MMDDYYYY) is passed through to generators that derive part of
 * the value from it — Connecticut prefixes the DCF with the issue date in
 * YYMMDD, so a DCF minted without it would not agree with the DBD on the same
 * card. Generators that ignore the argument are unaffected.
 */
export function generateStateDiscriminator(stateCode?: string, issueDateStr?: string): string {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DCF) {
    return AAMVA_STATE_RULES[stateCode].generators!.DCF(issueDateStr);
  }
  return generateDocumentDiscriminator();
}

export function generateStateLicenseNumber(stateCode?: string): string {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DAQ) {
    return AAMVA_STATE_RULES[stateCode].generators!.DAQ();
  }
  let s = "";
  for (let i = 0; i < 9; i++) s += secureGetRandomInt(10);
  return s;
}

export function generateStateCardRevisionDate(
  stateCode?: string,
  issueDateStr?: string
): string | null {
  if (stateCode && AAMVA_STATE_RULES[stateCode]?.generators?.DDB) {
    return AAMVA_STATE_RULES[stateCode].generators!.DDB(issueDateStr);
  }
  return null;
}

export function generateAAMVAPayload(
  stateCode: string,
  version: string,
  fields: AAMVAField[],
  inputData: Record<string, string>,
  options: GenerateOptions = {}
): string {
  const strictMode = options.strictMode === true;
  const subfileType = options.subfileType || "DL";

  // Work on a copy. This used to normalise and auto-fill the caller's object in
  // place, so generating a preview quietly rewrote the values the caller still
  // held — an undeclared side effect for a function that returns a string.
  const dataObj: Record<string, string> = { ...inputData };

  if (!AAMVA_STATES[stateCode]) throw new Error(`Unknown state code: ${stateCode}`);

  if (!isJurisdictionSupported(stateCode)) {
    throw new Error(`Unsupported jurisdiction for generation: ${stateCode}`);
  }

  if (!AAMVA_VERSIONS[version]) throw new Error(`Unsupported AAMVA version: ${version}`);

  if (strictMode) {
    const jurisdictionVersion = AAMVA_STATES[stateCode].aamvaVersion;
    if (version !== jurisdictionVersion) {
      throw new Error(
        `Strict Mode: version ${version} does not match ${stateCode} compliance profile (${jurisdictionVersion})`
      );
    }
  }

  if (options.autoGenerateDiscriminator && AAMVA_STATE_RULES[stateCode]?.generators) {
    const generators = AAMVA_STATE_RULES[stateCode].generators!;
    const presentCodes = new Set(fields.map((f) => f.code));
    for (const [code, generator] of Object.entries(generators)) {
      if (!AUTO_GENERATED_CODES.has(code)) continue;
      if (!presentCodes.has(code) || dataObj[code]) continue;
      dataObj[code] = code === "DDB" ? generator(dataObj.DBD) : generator();
    }
  }

  if (options.autoGenerateDiscriminator && !dataObj.DCF && fields.some((f) => f.code === "DCF")) {
    dataObj.DCF = generateDocumentDiscriminator();
  }

  const encoding = getJurisdictionEncoding(stateCode);

  // Normalise before the mandatory/format checks so values that arrive from an
  // import or a scan are judged on their real content. Decoded AAMVA values
  // carry the encoder's fixed-width space padding, and a required field holding
  // nothing but whitespace is missing, not present.
  for (const field of fields) {
    const raw = dataObj[field.code];
    if (raw) {
      let val = raw;
      // Jurisdiction subfile values are opaque: a decoded New York card carries
      // a mixed-case blob in ZNB, and upper-casing it — as the AAMVA text rule
      // would — silently rewrites data whose meaning we do not know.
      const isOpaque = field.subfile === "jurisdiction";
      if (!isOpaque && ["string", "char", "zip"].includes(field.type)) val = val.toUpperCase();
      dataObj[field.code] = val
        .normalize("NFKD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[^\x20-\x7e]/g, "")
        // eslint-disable-next-line no-control-regex
        .replace(/[\x00-\x1f\x7f]/g, "")
        .trim();
    }
  }

  const mandatoryFields = getMandatoryFields(stateCode, version);
  const missing = mandatoryFields
    .filter((f) => !dataObj[f.code])
    .map((f) => `${f.label} (${f.code})`);

  if (missing.length > 0) {
    throw new Error(
      `Missing mandatory fields for ${stateCode} (v${version}): ${missing.join(", ")}`
    );
  }

  if (dataObj.DAJ && dataObj.DAJ !== stateCode) {
    if (strictMode)
      throw new Error(`Strict Mode: DAJ (${dataObj.DAJ}) must match state code (${stateCode})`);
    dataObj.DAJ = stateCode;
  }

  // `evaluateFieldValue` rather than `validateFieldValue`, so the jurisdiction
  // rule packs are consulted here too. They were previously only reachable from
  // the UI, which meant strict mode surfaced a pack warning in the validation
  // panel and then generated the payload anyway — despite strict mode being
  // documented as "warnings are treated as errors and block generation".
  const invalidFields: string[] = [];
  const advisories: string[] = [];
  for (const field of fields) {
    const val = dataObj[field.code];
    if (!val) continue;
    // Evaluated without strict promotion so an advisory stays distinguishable
    // from a hard failure and can be reported with its own explanation below.
    const result = evaluateFieldValue(field, val, stateCode);
    if (!result.ok) {
      invalidFields.push(`${field.label} (${field.code})`);
    } else if (result.severity === "warning") {
      advisories.push(`${field.label} (${field.code}): ${result.message}`);
    }
  }

  if (invalidFields.length > 0) {
    throw new Error(
      `Invalid field values for ${stateCode} (v${version}): ${invalidFields.join(", ")}`
    );
  }

  const crossFieldIssues = validateCrossFieldConsistency(dataObj, fields, stateCode);
  const blockingCrossFieldIssues = crossFieldIssues.filter(
    (issue) => issue.severity === "error" || (strictMode && issue.severity === "warning")
  );

  if (blockingCrossFieldIssues.length > 0) {
    const details = blockingCrossFieldIssues
      .map((issue) => `[${issue.severity.toUpperCase()}] ${issue.message}`)
      .join(" ");
    throw new Error(`Cross-field validation failed for ${stateCode} (v${version}): ${details}`);
  }

  // Reported last, so a hard field error or a cross-field contradiction — both
  // more actionable — is what the user sees first when several things are wrong.
  if (strictMode && advisories.length > 0) {
    throw new Error(
      `Strict Mode: jurisdiction advisories for ${stateCode} (v${version}): ${advisories.join(" ")}`
    );
  }

  const stateDef = AAMVA_STATES[stateCode];
  const iin = stateDef.IIN;
  // Counts the issuer's own revisions of its implementation, independently of
  // the AAMVA version. "00" is the right default for an issuer we have never
  // seen a card from; New York emits "04".
  const jurisVersion = encoding?.jurisdictionVersion ?? "00";

  const compliance = "@";
  const dataElementSeparator = "\n";
  const recordSeparator = "\x1e";
  const segmentTerminator = "\r";
  const fileType = "ANSI ";

  const header =
    compliance +
    dataElementSeparator +
    recordSeparator +
    segmentTerminator +
    fileType +
    iin +
    version +
    jurisVersion;

  // The DL/ID subfile carries AAMVA-standard elements; a jurisdiction's own Z*
  // elements are a separate subfile with its own directory entry. Writing them
  // into the DL subfile would put codes the standard does not define where a
  // reader expects standard ones.
  const primaryFields = fields.filter((f) => f.subfile !== "jurisdiction");
  const jurisdictionFields = fields.filter((f) => f.subfile === "jurisdiction");

  const orderedPrimaryFields = orderFields(primaryFields, encoding?.elementOrder);
  const padPostal = shouldPadPostalCode(stateCode);

  const buildSubfile = (type: string, subfileFields: AAMVAField[]): string => {
    let out = type;
    for (const field of subfileFields) {
      let val = dataObj[field.code];
      if (val === undefined || val === "") continue;
      if (field.code === "DAK" && padPostal) {
        const stripped = val.replace(/-/g, "");
        val = stripped.padEnd(11, " ").substring(0, 11);
      } else if (field.code === "DAK") {
        val = val.replace(/-/g, "");
      }
      out += field.code + val + dataElementSeparator;
    }
    return out + segmentTerminator;
  };

  const subfiles: Array<{ type: string; data: string }> = [
    { type: subfileType, data: buildSubfile(subfileType, orderedPrimaryFields) }
  ];

  // Emitted only when the user actually supplied a value. A jurisdiction
  // subfile holding nothing but its own type byte is not what the DMV writes,
  // and it would cost every other consumer a directory entry to skip.
  const jurisdictionType = encoding?.jurisdictionSubfile?.type;
  if (jurisdictionType && jurisdictionFields.some((f) => dataObj[f.code])) {
    subfiles.push({
      type: jurisdictionType,
      data: buildSubfile(jurisdictionType, jurisdictionFields)
    });
  }

  const numEntries = subfiles.length.toString().padStart(2, "0");
  // The directory grows with the number of entries, so the first subfile no
  // longer starts at a fixed offset — it starts after however many 10-byte
  // entries the header declares.
  let offset = 21 + subfiles.length * 10;

  const directory: string[] = [];
  for (const subfile of subfiles) {
    const length = byteLength(subfile.data);
    if (length > 9999)
      throw new Error("Generated subfile exceeds 4-digit directory length limit (9999 bytes).");
    directory.push(subfile.type + pad4(offset) + pad4(length));
    offset += length;
  }

  if (offset > 9999) {
    throw new Error("Generated payload exceeds the 4-digit directory offset limit (9999 bytes).");
  }

  const payload = header + numEntries + directory.join("") + subfiles.map((s) => s.data).join("");

  if (strictMode) {
    const strictStructure = validateAAMVAPayloadStructure(payload, true);
    if (!strictStructure.ok) {
      throw new Error(
        `Strict Mode: generated payload structure is invalid (${strictStructure.error})`
      );
    }
  }

  return payload;
}
