// Regenerates the conformance test vectors under src/core/conformance/vectors/.
// Run with `node scripts/gen-vectors.mjs` after intentional encoder changes;
// the vectors are checked in and serve as byte-for-byte regression baselines.
// All inputs are synthetic — never use real PII.

import { generateAAMVAPayload } from "../src/core/generator.ts";
import { getFieldsForStateAndVersion } from "../src/core/schema.ts";
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT_DIR = resolve(ROOT, "src/core/conformance/vectors");
mkdirSync(OUT_DIR, { recursive: true });

// Synthetic, deterministic input. NO real PII.
const baseRecord = {
  DCS: "DOE",
  DAC: "JANE",
  DAD: "Q",
  DAA: "DOE,JANE,Q",
  DAQ: "D1234567",
  DCF: "ABCDEFGH1234",
  DBA: "01012030",
  DBB: "01011990",
  DBD: "01012024",
  DBC: "2",
  DAY: "BRO",
  DAZ: "BRO",
  DAU: "510",
  DAW: "150",
  DAG: "123 MAIN ST",
  DAI: "ANYTOWN",
  DAK: "00000",
  DCG: "USA",
  DCA: "C",
  DCB: "NONE",
  DCD: "NONE",
  DDE: "N",
  DDF: "N",
  DDG: "N",
  DDK: "1",
  DDL: "0"
};

const cases = [
  { id: "ca-v10-dl-baseline", state: "CA", version: "10", subfileType: "DL", DAQ: "D1234567" },
  { id: "ny-v09-dl-baseline", state: "NY", version: "09", subfileType: "DL", DAQ: "123456789" },
  { id: "tx-v10-dl-baseline", state: "TX", version: "10", subfileType: "DL", DAQ: "12345678" },
  { id: "fl-v10-dl-baseline", state: "FL", version: "10", subfileType: "DL", DAQ: "D123456789012" },
  { id: "il-v09-id-baseline", state: "IL", version: "09", subfileType: "ID", DAQ: "D123456789012" },
  { id: "wa-v09-dl-baseline", state: "WA", version: "09", subfileType: "DL", DAQ: "ABCDEFG12345" }
];

for (const c of cases) {
  const fields = getFieldsForStateAndVersion(c.state, c.version);
  const rec = { ...baseRecord, DAJ: c.state, DAQ: c.DAQ };
  const payload = generateAAMVAPayload(c.state, c.version, fields, rec, {
    autoGenerateDiscriminator: false,
    subfileType: c.subfileType
  });
  const vector = {
    id: c.id,
    state: c.state,
    version: c.version,
    subfileType: c.subfileType,
    description: "Synthetic regression baseline (no PII).",
    input: rec,
    expectedBytes: payload
  };
  const path = resolve(OUT_DIR, `${c.id}.json`);
  writeFileSync(path, JSON.stringify(vector, null, 2) + "\n");
  console.log("wrote", path);
}
